/* ============================================================================
   data.js — Inhalts-Datenbasis für "In den Himmel"
   Reine Daten, global (kein ES-Modul, läuft unter file://).
   Höhen (altitude_m) in METERN. Geprüfte Werte; `note` kennzeichnet die Art.
   `emoji` dient als Platzhalter, solange kein freigestelltes Foto (`img`) da ist.
   ========================================================================== */

/* Distanz-Hilfskonstanten (Meter) für lesbare Entfernungsangaben. */
const LY = 9.4607e15;   // Meter pro Lichtjahr
const AU = 1.496e11;    // Meter pro Astronomische Einheit

const SKY_DATA = [

  /* ---------- TIERE ---------- */
  { id:"spatz", cat:"bird", emoji:"🐦", altitude_m:50,
    name:{de:"Haussperling", en:"House Sparrow"}, sci:"Passer domesticus",
    note:"typisch",
    fact:{de:"Spatzen fliegen meist nur wenige Meter über dem Boden – ihr Reich ist die Hecke, nicht der Himmel.",
          en:"Sparrows usually fly just a few metres above the ground – their realm is the hedge, not the sky."},
    img:"images/spatz.png", credit:"Wikimedia Commons", license:"CC BY-SA",
    source:"https://en.wikipedia.org/wiki/House_sparrow" },

  { id:"schwalbe", cat:"bird", emoji:"🐦", altitude_m:200,
    name:{de:"Rauchschwalbe", en:"Barn Swallow"}, sci:"Hirundo rustica",
    note:"typisch",
    fact:{de:"Jagt Insekten im Tiefflug. Bei gutem Wetter steigen die Beuteinsekten höher – und die Schwalben mit ihnen.",
          en:"Hunts insects in low flight. In fine weather its prey rises higher – and the swallows follow."},
    img:"images/schwalbe.png", credit:"Wikimedia Commons", license:"CC BY-SA",
    source:"https://en.wikipedia.org/wiki/Barn_swallow" },

  { id:"marienkaefer", cat:"insect", emoji:"🐞", altitude_m:1100,
    name:{de:"Marienkäfer", en:"Ladybird / Ladybug"}, sci:"Coccinellidae",
    note:"extremwert",
    fact:{de:"Radarstudien zeigten Marienkäfer bis 1.100 m Höhe – die meisten bleiben aber zwischen 150 und 500 m.",
          en:"Radar studies tracked ladybirds up to 1,100 m – though most stay between 150 and 500 m."},
    img:"images/marienkaefer.png", credit:"Wikimedia Commons", license:"CC BY-SA",
    source:"https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0082278" },

  { id:"mauersegler", cat:"bird", emoji:"🐦", altitude_m:3000,
    name:{de:"Mauersegler", en:"Common Swift"}, sci:"Apus apus",
    note:"typisch",
    fact:{de:"Schläft im Flug: Mauersegler steigen abends per Radar nachweisbar bis ~3 km auf und verbringen die Nacht in der Luft.",
          en:"Sleeps on the wing: at dusk swifts climb to ~3 km (radar-confirmed) and spend the whole night airborne."},
    img:"images/mauersegler.png", credit:"Wikimedia Commons", license:"CC BY-SA",
    source:"https://www.sciencedirect.com/science/article/pii/S0003347212005556" },

  { id:"distelfalter", cat:"insect", emoji:"🦋", altitude_m:3000,
    name:{de:"Distelfalter", en:"Painted Lady"}, sci:"Vanessa cardui",
    note:"typisch",
    fact:{de:"Zieht in Höhen von 1.000–3.000 m über Tausende Kilometer – einer der weitesten Wanderfalter der Welt.",
          en:"Migrates at 1,000–3,000 m over thousands of kilometres – one of the longest-distance migrating butterflies."},
    img:"images/distelfalter.png", credit:"Wikimedia Commons", license:"CC BY-SA",
    source:"https://butterfly-conservation.org/news-and-blog/painted-lady-migration-secrets-revealed" },

  { id:"fledermaus", cat:"bat", emoji:"🦇", altitude_m:3300,
    name:{de:"Mexikanische Bulldoggfledermaus", en:"Mexican Free-tailed Bat"}, sci:"Tadarida brasiliensis",
    note:"typisch",
    fact:{de:"Die höchstfliegende Fledermaus: jagt nachtaktiv Wanderfalter per Radar nachgewiesen bis ~3.300 m.",
          en:"The highest-flying bat: hunts migrating moths at night, radar-tracked up to ~3,300 m."},
    img:"images/fledermaus.png", credit:"Wikimedia Commons", license:"CC BY-SA",
    source:"https://academic.oup.com/jmammal/article-abstract/54/4/807/844057" },

  { id:"monarch", cat:"insect", emoji:"🦋", altitude_m:3600,
    name:{de:"Monarchfalter", en:"Monarch Butterfly"}, sci:"Danaus plexippus",
    note:"bodenhoehe",
    fact:{de:"Überwintert massenhaft in mexikanischen Oyamel-Wäldern auf 2.400–3.600 m. Das ist Standort­höhe, nicht Flughöhe.",
          en:"Overwinters in masses in Mexican oyamel forests at 2,400–3,600 m. That is ground elevation, not flight altitude."},
    img:"images/monarch.png", credit:"Wikimedia Commons", license:"CC BY-SA",
    source:"https://en.wikipedia.org/wiki/Monarch_butterfly_migration" },

  { id:"spinne", cat:"spider", emoji:"🕷️", altitude_m:4500,
    name:{de:"Ballooning-Spinne", en:"Ballooning Spider"}, sci:"diverse Arten",
    note:"extremwert",
    fact:{de:"Lässt sich an Seidenfäden vom Wind tragen ('Ballooning'). In Luftproben bis ~4.500 m als Teil des Aeroplanktons gefunden.",
          en:"Drifts on silk threads carried by the wind ('ballooning'). Found in air samples up to ~4,500 m as part of the aeroplankton."},
    img:"images/spinne.png", credit:"Wikimedia Commons", license:"CC BY-SA",
    source:"https://en.wikipedia.org/wiki/Ballooning_(spider)" },

  { id:"steinadler", cat:"bird", emoji:"🦅", altitude_m:4500,
    name:{de:"Steinadler", en:"Golden Eagle"}, sci:"Aquila chrysaetos",
    note:"typisch",
    fact:{de:"Nutzt Thermik und Hangaufwinde und kreist regelmäßig bis ~4.500 m – höher als die meisten Greifvögel.",
          en:"Rides thermals and ridge lift, regularly soaring to ~4,500 m – higher than most birds of prey."},
    img:"images/steinadler.png", credit:"Wikimedia Commons", license:"CC BY-SA",
    source:"https://pmc.ncbi.nlm.nih.gov/articles/PMC9179650/" },

  { id:"bartgeier", cat:"bird", emoji:"🦅", altitude_m:7300,
    name:{de:"Bartgeier", en:"Bearded Vulture"}, sci:"Gypaetus barbatus",
    note:"typisch",
    fact:{de:"Im Himalaya regelmäßig über 7 km unterwegs. Lässt Knochen aus der Höhe auf Felsen fallen, um an das Mark zu kommen.",
          en:"Regularly flies above 7 km in the Himalayas. Drops bones from height onto rocks to reach the marrow."},
    img:"images/bartgeier.png", credit:"Wikimedia Commons", license:"CC BY-SA",
    source:"https://en.wikipedia.org/wiki/Bearded_vulture" },

  { id:"streifengans", cat:"bird", emoji:"🪿", altitude_m:7290,
    name:{de:"Streifengans", en:"Bar-headed Goose"}, sci:"Anser indicus",
    note:"extremwert",
    fact:{de:"Überquert den Himalaya. Eine GPS-Gans erreichte 7.290 m – doch 95 % aller Messungen lagen unter 5.500 m.",
          en:"Crosses the Himalayas. One GPS-tracked goose reached 7,290 m – yet 95% of all fixes were below 5,500 m."},
    img:"images/streifengans.png", credit:"Wikimedia Commons", license:"CC BY-SA",
    source:"https://www.pnas.org/doi/10.1073/pnas.1017295108" },

  { id:"singschwan", cat:"bird", emoji:"🦢", altitude_m:8000,
    name:{de:"Singschwan", en:"Whooper Swan"}, sci:"Cygnus cygnus",
    note:"extremereignis",
    fact:{de:"Ein Pilot und das Radar erfassten Singschwäne über 8 km über den Britischen Inseln – außergewöhnlich für so schwere Vögel.",
          en:"A pilot and radar recorded whooper swans above 8 km over the British Isles – extraordinary for such heavy birds."},
    img:"images/singschwan.png", credit:"Wikimedia Commons", license:"CC BY-SA",
    source:"https://en.wikipedia.org/wiki/Whooper_swan" },

  { id:"alpendohle", cat:"bird", emoji:"🐦‍⬛", altitude_m:8200,
    name:{de:"Alpendohle", en:"Alpine Chough"}, sci:"Pyrrhocorax graculus",
    note:"extremereignis",
    fact:{de:"Folgte Bergsteigern am Mount Everest bis 8.200 m. Brütet höher als jeder andere Vogel – bis 6.500 m.",
          en:"Followed climbers up Mount Everest to 8,200 m. Nests higher than any other bird – up to 6,500 m."},
    img:"images/alpendohle.png", credit:"Wikimedia Commons", license:"CC BY-SA",
    source:"https://en.wikipedia.org/wiki/Alpine_chough" },

  { id:"doppelschnepfe", cat:"bird", emoji:"🐦", altitude_m:8700,
    name:{de:"Doppelschnepfe", en:"Great Snipe"}, sci:"Gallinago media",
    note:"extremwert",
    fact:{de:"Ein getracktes Individuum stieg auf 8.700 m – möglicherweise der höchste je per Sender gemessene Zugvogel.",
          en:"One tracked bird climbed to 8,700 m – possibly the highest altitude ever measured for a migrating bird by tag."},
    img:"images/doppelschnepfe.png", credit:"Wikimedia Commons", license:"CC BY-SA",
    source:"https://www.sciencedirect.com/science/article/pii/S0960982221007454" },

  { id:"hummel", cat:"insect", emoji:"🐝", altitude_m:9000,
    name:{de:"Hummel", en:"Bumblebee"}, sci:"Bombus spp.",
    note:"laborwert",
    fact:{de:"Im Unterdruck-Kammerversuch (2014) hielten Alpenhummeln Schwebflug bei simulierten über 9.000 m – höher als der Everest.",
          en:"In a 2014 low-pressure chamber test, alpine bumblebees hovered at a simulated 9,000 m+ – higher than Everest."},
    img:"images/hummel.png", credit:"Wikimedia Commons", license:"CC BY-SA",
    source:"https://royalsocietypublishing.org/doi/10.1098/rsbl.2013.0922" },

  { id:"kranich", cat:"bird", emoji:"🐦", altitude_m:10000,
    name:{de:"Kranich", en:"Common Crane"}, sci:"Grus grus",
    note:"extremwert",
    fact:{de:"Kann über Gebirgspässe bis ~10.000 m steigen – gilt als zweithöchster Vogel nach dem Sperbergeier. Normal fliegt er viel tiefer.",
          en:"Can climb to ~10,000 m over mountain passes – reckoned the second-highest bird after Rüppell's vulture. Normally flies far lower."},
    img:"images/kranich.png", credit:"Wikimedia Commons", license:"CC BY-SA",
    source:"https://en.wikipedia.org/wiki/Common_crane" },

  { id:"sperbergeier", cat:"bird", emoji:"🦅", altitude_m:11300,
    name:{de:"Sperbergeier", en:"Rüppell's Vulture"}, sci:"Gyps rueppellii",
    note:"extremereignis",
    fact:{de:"Hält den Vogel-Höhenrekord: 11.300 m – nachgewiesen 1973 durch eine Kollision mit einem Flugzeugtriebwerk über Westafrika.",
          en:"Holds the bird altitude record: 11,300 m – proven in 1973 by a collision with a jet engine over West Africa."},
    img:"images/sperbergeier.png", credit:"Wikimedia Commons", license:"CC BY-SA",
    source:"https://www.guinnessworldrecords.com/world-records/70927-highest-flying-birds" },

  /* ---------- REFERENZ: BAUWERKE & BERGE ---------- */
  { id:"burj", cat:"reference", emoji:"🏙️", altitude_m:828,
    name:{de:"Burj Khalifa", en:"Burj Khalifa"}, sci:"",
    note:"referenz",
    fact:{de:"Mit 828 m das höchste Bauwerk der Welt. Selbst seine Spitze liegt noch im Reich der niedrig fliegenden Vögel.",
          en:"At 828 m the tallest structure on Earth. Even its tip is still in the realm of low-flying birds."},
    img:"images/burj.png", credit:"Wikimedia Commons", license:"CC BY-SA",
    source:"https://en.wikipedia.org/wiki/Burj_Khalifa" },

  { id:"montblanc", cat:"reference", emoji:"⛰️", altitude_m:4808,
    name:{de:"Mont Blanc", en:"Mont Blanc"}, sci:"",
    note:"referenz",
    fact:{de:"Höchster Gipfel der Alpen mit 4.808 m – auf dieser Höhe kreisen Steinadler und Bartgeier.",
          en:"The highest Alpine summit at 4,808 m – at this height golden eagles and bearded vultures soar."},
    img:"images/montblanc.png", credit:"Wikimedia Commons", license:"CC BY-SA",
    source:"https://en.wikipedia.org/wiki/Mont_Blanc" },

  { id:"everest", cat:"reference", emoji:"🏔️", altitude_m:8849,
    name:{de:"Mount Everest", en:"Mount Everest"}, sci:"",
    note:"referenz",
    fact:{de:"Mit 8.849 m der höchste Berg der Erde. Sein Gipfel ragt in die Zone, in der nur noch Geier und Gänse fliegen.",
          en:"At 8,849 m the highest mountain on Earth. Its summit reaches the zone where only vultures and geese still fly."},
    img:"images/everest.png", credit:"Wikimedia Commons", license:"CC BY-SA",
    source:"https://en.wikipedia.org/wiki/Mount_Everest" },

  /* ---------- FLUGZEUGE & LUFTFAHRT ---------- */
  { id:"drohne", cat:"aircraft", emoji:"🛸", altitude_m:120,
    name:{de:"Consumer-Drohne", en:"Consumer Drone"}, sci:"",
    note:"referenz",
    fact:{de:"In der EU dürfen Hobby-Drohnen meist nur bis 120 m steigen – knapp über den Baumwipfeln.",
          en:"In the EU, hobby drones may usually fly only up to 120 m – just above the treetops."},
    img:"images/drohne.png", credit:"Wikimedia Commons", license:"CC BY-SA",
    source:"https://www.easa.europa.eu/en/domains/civil-drones" },

  { id:"jet", cat:"aircraft", emoji:"✈️", altitude_m:11500,
    name:{de:"Verkehrsflugzeug", en:"Airliner"}, sci:"",
    note:"typisch",
    fact:{de:"Reiseflughöhe der meisten Jets: 10–12 km. Genau hier kollidierte 1973 der Sperbergeier mit einem Triebwerk.",
          en:"Cruising altitude of most jets: 10–12 km. This is exactly where Rüppell's vulture hit an engine in 1973."},
    img:"images/jet.png", credit:"Wikimedia Commons", license:"CC BY-SA",
    source:"https://www.britannica.com/topic/How-High-Does-An-Airplane-Fly" },

  { id:"helikopter", cat:"aircraft", emoji:"🚁", altitude_m:12954,
    name:{de:"Hubschrauber-Höhenrekord", en:"Helicopter Altitude Record"}, sci:"",
    note:"extremereignis",
    fact:{de:"Fred North flog 2002 einen Hubschrauber auf 12.954 m. In dieser dünnen Luft finden Rotoren kaum noch Halt.",
          en:"Fred North flew a helicopter to 12,954 m in 2002. In such thin air the rotors barely find any grip."},
    img:"images/helikopter.png", credit:"Wikimedia Commons", license:"CC BY-SA",
    source:"https://en.wikipedia.org/wiki/List_of_flight_altitude_records" },

  { id:"concorde", cat:"aircraft", emoji:"✈️", altitude_m:18000,
    name:{de:"Concorde", en:"Concorde"}, sci:"",
    note:"typisch",
    fact:{de:"Das Überschall-Verkehrsflugzeug flog auf bis zu 18 km – so hoch, dass Passagiere die Erdkrümmung sehen konnten.",
          en:"The supersonic airliner cruised at up to 18 km – high enough for passengers to see the curvature of the Earth."},
    img:"images/concorde.png", credit:"Wikimedia Commons", license:"CC BY-SA",
    source:"https://en.wikipedia.org/wiki/Concorde" },

  { id:"u2", cat:"aircraft", emoji:"✈️", altitude_m:21000,
    name:{de:"U-2 Aufklärungsflugzeug", en:"U-2 Spy Plane"}, sci:"",
    note:"typisch",
    fact:{de:"Operiert auf über 21 km. Die Piloten tragen Druckanzüge wie Astronauten – am 'Rand des Weltraums'.",
          en:"Operates above 21 km. Its pilots wear pressure suits like astronauts – at the 'edge of space'."},
    img:"images/u2.png", credit:"Wikimedia Commons", license:"CC BY-SA",
    source:"https://en.wikipedia.org/wiki/Lockheed_U-2" },

  { id:"ballon", cat:"aircraft", emoji:"🎈", altitude_m:21290,
    name:{de:"Heißluftballon-Rekord", en:"Hot-air Balloon Record"}, sci:"",
    note:"extremereignis",
    fact:{de:"Vijaypat Singhania stieg 2005 mit einem Heißluftballon auf 21.290 m – Weltrekord.",
          en:"Vijaypat Singhania reached 21,290 m in a hot-air balloon in 2005 – a world record."},
    img:"images/ballon.png", credit:"Wikimedia Commons", license:"CC BY-SA",
    source:"https://www.fai.org/" },

  { id:"sr71", cat:"aircraft", emoji:"✈️", altitude_m:25900,
    name:{de:"SR-71 Blackbird", en:"SR-71 Blackbird"}, sci:"",
    note:"typisch",
    fact:{de:"Das schnellste je gebaute Strahlflugzeug operierte auf ~25,9 km und mit über dreifacher Schallgeschwindigkeit.",
          en:"The fastest jet aircraft ever built operated at ~25.9 km and over three times the speed of sound."},
    img:"images/sr71.png", credit:"Wikimedia Commons", license:"Public Domain",
    source:"https://en.wikipedia.org/wiki/Lockheed_SR-71_Blackbird" },

  { id:"wetterballon", cat:"aircraft", emoji:"🎈", altitude_m:35000,
    name:{de:"Wetterballon", en:"Weather Balloon"}, sci:"",
    note:"typisch",
    fact:{de:"Steigt bis ~35 km, bis er sich im Vakuum auf Hausgröße aufbläht und platzt. Die Instrumente fallen am Fallschirm zurück.",
          en:"Rises to ~35 km until it swells to the size of a house in near-vacuum and bursts. The instruments parachute back."},
    img:"images/wetterballon.png", credit:"Wikimedia Commons", license:"CC BY-SA",
    source:"https://en.wikipedia.org/wiki/Weather_balloon" },

  { id:"mig25", cat:"aircraft", emoji:"✈️", altitude_m:37650,
    name:{de:"MiG-25 Höhenrekord", en:"MiG-25 Altitude Record"}, sci:"",
    note:"extremereignis",
    fact:{de:"Alexander Fedotow trieb eine MiG-25 1977 auf 37.650 m – bis heute Höhenrekord für Strahljäger im Steigflug.",
          en:"Alexander Fedotov pushed a MiG-25 to 37,650 m in 1977 – still the altitude record for a jet aircraft."},
    img:"images/mig25.png", credit:"Wikimedia Commons", license:"CC BY-SA",
    source:"https://en.wikipedia.org/wiki/List_of_flight_altitude_records" },

  { id:"stratos", cat:"aircraft", emoji:"🪂", altitude_m:39044,
    name:{de:"Red Bull Stratos (Baumgartner)", en:"Red Bull Stratos (Baumgartner)"}, sci:"",
    note:"extremereignis",
    fact:{de:"2012 sprang Felix Baumgartner aus 39.044 m aus einer Ballonkapsel – und durchbrach im freien Fall die Schallmauer.",
          en:"In 2012 Felix Baumgartner jumped from 39,044 m out of a balloon capsule – breaking the sound barrier in free fall."},
    img:"images/stratos.png", credit:"Wikimedia Commons", license:"CC BY-SA",
    source:"https://en.wikipedia.org/wiki/Red_Bull_Stratos" },

  { id:"eustace", cat:"aircraft", emoji:"🪂", altitude_m:41419,
    name:{de:"Alan Eustace Stratosphären-Sprung", en:"Alan Eustace Stratospheric Jump"}, sci:"",
    note:"extremereignis",
    fact:{de:"2014 übertraf Alan Eustace Baumgartner mit einem Sprung aus 41.419 m – höchster Fallschirmsprung der Geschichte.",
          en:"In 2014 Alan Eustace topped Baumgartner with a jump from 41,419 m – the highest parachute jump in history."},
    img:"images/eustace.png", credit:"Wikimedia Commons", license:"CC BY-SA",
    source:"https://en.wikipedia.org/wiki/Alan_Eustace" },

  /* ---------- GRENZE ZUM WELTRAUM ---------- */
  { id:"karman", cat:"reference", emoji:"🌌", altitude_m:100000,
    name:{de:"Kármán-Linie", en:"Kármán Line"}, sci:"",
    note:"referenz",
    fact:{de:"Bei 100 km gilt offiziell die Grenze zum Weltraum. Darüber gibt es zu wenig Luft, um zu fliegen – man muss eine Umlaufbahn fallen.",
          en:"At 100 km lies the official boundary of space. Above it there is too little air to fly – you must orbit by falling."},
    img:"images/karman.png", credit:"NASA", license:"Public Domain",
    source:"https://en.wikipedia.org/wiki/K%C3%A1rm%C3%A1n_line" },

  /* ---------- RAUMFAHRT KATEGORIE 1: BEMANNT ---------- */
  { id:"x15", cat:"manned", emoji:"🚀", altitude_m:108000,
    name:{de:"X-15 (höchster bemannter Flugzeug-Flug)", en:"X-15 (highest crewed aeroplane flight)"}, sci:"",
    note:"extremereignis",
    fact:{de:"Das Raketenflugzeug X-15 erreichte 1963 mit Joseph Walker 108 km – ein Flugzeugstart, der bis in den Weltraum führte.",
          en:"The X-15 rocket plane reached 108 km with Joseph Walker in 1963 – an aeroplane that took off and flew into space."},
    img:"images/x15.png", credit:"NASA", license:"Public Domain",
    source:"https://en.wikipedia.org/wiki/North_American_X-15" },

  { id:"iss", cat:"manned", emoji:"🛰️", altitude_m:408000,
    name:{de:"Internationale Raumstation (ISS)", en:"International Space Station (ISS)"}, sci:"",
    note:"referenz",
    fact:{de:"Seit dem Jahr 2000 dauerhaft bemannt. Sie umkreist die Erde in ~408 km Höhe alle 90 Minuten einmal.",
          en:"Continuously crewed since 2000. It orbits Earth at ~408 km, completing one lap every 90 minutes."},
    img:"images/iss.png", credit:"NASA", license:"Public Domain",
    source:"https://en.wikipedia.org/wiki/International_Space_Station" },

  { id:"gemini11", cat:"manned", emoji:"👨‍🚀", altitude_m:1373000,
    name:{de:"Gemini 11 (höchste bemannte Erdumlaufbahn)", en:"Gemini 11 (highest crewed Earth orbit)"}, sci:"",
    note:"extremereignis",
    fact:{de:"1966 erreichte Gemini 11 einen Bahnscheitel von 1.373 km – die höchste bemannte Erdumlaufbahn vor Apollo.",
          en:"In 1966 Gemini 11 reached an apogee of 1,373 km – the highest crewed Earth orbit before Apollo."},
    img:"images/gemini11.png", credit:"NASA", license:"Public Domain",
    source:"https://en.wikipedia.org/wiki/Gemini_11" },

  { id:"mond", cat:"manned", emoji:"🌕", altitude_m:384400000,
    name:{de:"Der Mond (Apollo-Landungen)", en:"The Moon (Apollo landings)"}, sci:"",
    note:"referenz",
    fact:{de:"384.400 km entfernt. Zwölf Menschen sind zwischen 1969 und 1972 auf ihm gelandet – die bislang fernste Reise.",
          en:"384,400 km away. Twelve humans landed on it between 1969 and 1972 – the farthest journey people have made."},
    img:"images/mond.png", credit:"NASA", license:"Public Domain",
    source:"https://en.wikipedia.org/wiki/Apollo_program" },

  { id:"apollo13", cat:"manned", emoji:"🧑‍🚀", altitude_m:400171000,
    name:{de:"Apollo 13 (entferntester Mensch)", en:"Apollo 13 (farthest humans)"}, sci:"",
    note:"extremereignis",
    fact:{de:"Auf der Notfall-Schleife um den Mond kam Apollo 13 1970 bis 400.171 km von der Erde – der Rekord der größten Menschen-Entfernung.",
          en:"On its emergency loop around the Moon, Apollo 13 reached 400,171 km from Earth in 1970 – the record distance for humans."},
    img:"images/apollo13.png", credit:"NASA", license:"Public Domain",
    source:"https://en.wikipedia.org/wiki/Apollo_13" },

  /* ---------- RAUMFAHRT KATEGORIE 2: UNBEMANNT ---------- */
  { id:"hubble", cat:"unmanned", emoji:"🔭", altitude_m:540000,
    name:{de:"Hubble-Weltraumteleskop", en:"Hubble Space Telescope"}, sci:"",
    note:"referenz",
    fact:{de:"Umkreist die Erde in ~540 km. Astronauten reparierten es fünfmal – das letzte von Menschen gewartete Teleskop.",
          en:"Orbits Earth at ~540 km. Astronauts serviced it five times – the last telescope ever maintained by humans."},
    img:"images/hubble.png", credit:"NASA", license:"Public Domain",
    source:"https://en.wikipedia.org/wiki/Hubble_Space_Telescope" },

  { id:"gps", cat:"unmanned", emoji:"🛰️", altitude_m:20200000,
    name:{de:"GPS-Satellit", en:"GPS Satellite"}, sci:"",
    note:"referenz",
    fact:{de:"Kreist in 20.200 km Höhe. Seine Atomuhren ticken so präzise, dass Einsteins Relativitätstheorie eingerechnet werden muss.",
          en:"Orbits at 20,200 km. Its atomic clocks are so precise that Einstein's relativity must be factored in."},
    img:"images/gps.png", credit:"NASA", license:"Public Domain",
    source:"https://en.wikipedia.org/wiki/Global_Positioning_System" },

  { id:"geo", cat:"unmanned", emoji:"📡", altitude_m:35786000,
    name:{de:"Geostationärer Satellit", en:"Geostationary Satellite"}, sci:"",
    note:"referenz",
    fact:{de:"In 35.786 km Höhe umkreist ein Satellit die Erde genau einmal pro Tag – und scheint daher am Himmel stillzustehen.",
          en:"At 35,786 km a satellite orbits Earth exactly once a day – so it appears to hang motionless in the sky."},
    img:"images/geo.png", credit:"NASA", license:"Public Domain",
    source:"https://en.wikipedia.org/wiki/Geostationary_orbit" },

  { id:"jwst", cat:"unmanned", emoji:"🔭", altitude_m:1500000000,
    name:{de:"James-Webb-Teleskop", en:"James Webb Space Telescope"}, sci:"",
    note:"referenz",
    fact:{de:"Steht 1,5 Mio. km von der Erde am Lagrange-Punkt L2 und blickt zurück bis zu den ersten Galaxien des Universums.",
          en:"Sits 1.5 million km from Earth at Lagrange point L2, looking back to the first galaxies of the universe."},
    img:"images/jwst.png", credit:"NASA", license:"Public Domain",
    source:"https://en.wikipedia.org/wiki/James_Webb_Space_Telescope" },

  { id:"curiosity", cat:"unmanned", emoji:"🤖", altitude_m:225000000000,
    name:{de:"Mars-Rover Curiosity", en:"Mars Rover Curiosity"}, sci:"",
    note:"referenz",
    fact:{de:"Rollt seit 2012 über den Mars – im Mittel ~225 Mio. km entfernt. Ein Funksignal braucht dorthin bis zu 22 Minuten.",
          en:"Has roamed Mars since 2012 – on average ~225 million km away. A radio signal takes up to 22 minutes to reach it."},
    img:"images/curiosity.png", credit:"NASA/JPL", license:"Public Domain",
    source:"https://en.wikipedia.org/wiki/Curiosity_(rover)" },

  { id:"voyager2", cat:"unmanned", emoji:"🛰️", altitude_m:21400000000000,
    name:{de:"Voyager 2", en:"Voyager 2"}, sci:"",
    note:"referenz",
    fact:{de:"1977 gestartet, verließ 2018 das Sonnensystem. Stand 2026 rund 21,4 Mrd. km (143 AE) entfernt – und sendet noch immer.",
          en:"Launched in 1977, it left the Solar System in 2018. As of 2026 about 21.4 billion km (143 AU) away – and still transmitting."},
    img:"images/voyager2.png", credit:"NASA/JPL", license:"Public Domain",
    source:"https://en.wikipedia.org/wiki/Voyager_2" },

  { id:"voyager1", cat:"unmanned", emoji:"🛰️", altitude_m:25800000000000,
    name:{de:"Voyager 1", en:"Voyager 1"}, sci:"",
    note:"extremereignis",
    fact:{de:"Das entfernteste von Menschen gebaute Objekt: Stand 2026 rund 25,8 Mrd. km (173 AE) im interstellaren Raum. Sein Funksignal braucht knapp einen ganzen Tag zu uns.",
          en:"The most distant human-made object: about 25.8 billion km (173 AU) in interstellar space as of 2026. Its radio signal takes almost a full day to reach us."},
    img:"images/voyager1.png", credit:"NASA/JPL", license:"Public Domain",
    source:"https://en.wikipedia.org/wiki/Voyager_1" },

  /* ---------- PLANETEN, SONNE & STERNE (Distanz-Anker) ---------- */
  { id:"sonne", cat:"star", emoji:"☀️", altitude_m:149600000000,
    name:{de:"Die Sonne", en:"The Sun"}, sci:"",
    note:"referenz",
    fact:{de:"149,6 Mio. km entfernt – das ist eine Astronomische Einheit (1 AE). Ihr Licht braucht 8 Minuten und 20 Sekunden bis zu uns.",
          en:"149.6 million km away – that is one Astronomical Unit (1 AU). Its light takes 8 minutes 20 seconds to reach us."},
    img:"images/sonne.png", credit:"NASA/SDO", license:"Public Domain",
    source:"https://science.nasa.gov/sun/" },

  { id:"merkur", cat:"planet", emoji:"🟤", altitude_m:155000000000,
    name:{de:"Merkur", en:"Mercury"}, sci:"",
    note:"referenz",
    fact:{de:"Im Mittel ~155 Mio. km entfernt – oft sogar weiter weg als die Sonne, weil er meist auf deren anderer Seite steht.",
          en:"On average ~155 million km away – often even farther than the Sun, because it usually sits on its far side."},
    img:"images/merkur.png", credit:"NASA", license:"Public Domain",
    source:"https://science.nasa.gov/mercury/" },

  { id:"venus", cat:"planet", emoji:"🟡", altitude_m:170000000000,
    name:{de:"Venus", en:"Venus"}, sci:"",
    note:"referenz",
    fact:{de:"Unser Nachbarplanet, im Mittel ~170 Mio. km entfernt. Bei größter Annäherung (38 Mio. km) kommt uns kein Planet näher.",
          en:"Our neighbouring planet, on average ~170 million km away. At closest approach (38 million km) no planet comes nearer."},
    img:"images/venus.png", credit:"NASA", license:"Public Domain",
    source:"https://science.nasa.gov/venus/" },

  { id:"mars", cat:"planet", emoji:"🔴", altitude_m:225000000000,
    name:{de:"Mars", en:"Mars"}, sci:"",
    note:"referenz",
    fact:{de:"Der Rote Planet, im Mittel ~225 Mio. km entfernt. Hier arbeiten Rover wie Curiosity – ein Funkbefehl ist bis zu 22 Minuten unterwegs.",
          en:"The Red Planet, on average ~225 million km away. Rovers like Curiosity work here – a radio command takes up to 22 minutes."},
    img:"images/mars.png", credit:"NASA", license:"Public Domain",
    source:"https://science.nasa.gov/mars/" },

  { id:"jupiter", cat:"planet", emoji:"🟠", altitude_m:779000000000,
    name:{de:"Jupiter", en:"Jupiter"}, sci:"",
    note:"referenz",
    fact:{de:"Der größte Planet, ~779 Mio. km entfernt. Hierher fliegt die 2024 gestartete Sonde Europa Clipper – Ankunft 2030.",
          en:"The largest planet, ~779 million km away. The Europa Clipper probe launched in 2024 is heading here – arriving 2030."},
    img:"images/jupiter.png", credit:"NASA", license:"Public Domain",
    source:"https://science.nasa.gov/jupiter/" },

  { id:"saturn", cat:"planet", emoji:"🪐", altitude_m:1432000000000,
    name:{de:"Saturn", en:"Saturn"}, sci:"",
    note:"referenz",
    fact:{de:"Der Ringplanet, ~1,4 Mrd. km entfernt. Sein Anblick ist über eine Stunde alt, wenn das Licht bei uns ankommt.",
          en:"The ringed planet, ~1.4 billion km away. Its image is over an hour old by the time the light reaches us."},
    img:"images/saturn.png", credit:"NASA", license:"Public Domain",
    source:"https://science.nasa.gov/saturn/" },

  { id:"uranus", cat:"planet", emoji:"🔵", altitude_m:2884000000000,
    name:{de:"Uranus", en:"Uranus"}, sci:"",
    note:"referenz",
    fact:{de:"Ein Eisriese, ~2,9 Mrd. km entfernt. Nur eine einzige Sonde war je dort: Voyager 2 im Jahr 1986.",
          en:"An ice giant, ~2.9 billion km away. Only one probe has ever visited: Voyager 2 in 1986."},
    img:"images/uranus.png", credit:"NASA", license:"Public Domain",
    source:"https://science.nasa.gov/uranus/" },

  { id:"neptun", cat:"planet", emoji:"🔵", altitude_m:4509000000000,
    name:{de:"Neptun", en:"Neptune"}, sci:"",
    note:"referenz",
    fact:{de:"Der äußerste Planet, ~4,5 Mrd. km entfernt. Das Sonnenlicht ist hier rund 900-mal schwächer als auf der Erde.",
          en:"The outermost planet, ~4.5 billion km away. Sunlight here is about 900 times weaker than on Earth."},
    img:"images/neptun.png", credit:"NASA", license:"Public Domain",
    source:"https://science.nasa.gov/neptune/" },

  { id:"pluto", cat:"planet", emoji:"⚪", altitude_m:5910000000000,
    name:{de:"Pluto (Zwergplanet)", en:"Pluto (dwarf planet)"}, sci:"",
    note:"referenz",
    fact:{de:"Im Mittel ~5,9 Mrd. km entfernt. Die Sonde New Horizons flog 2015 als erste an ihm vorbei.",
          en:"On average ~5.9 billion km away. The New Horizons probe made the first-ever flyby in 2015."},
    img:"images/pluto.png", credit:"NASA/JHUAPL", license:"Public Domain",
    source:"https://science.nasa.gov/dwarf-planets/pluto/" },

  { id:"proxima", cat:"star", emoji:"⭐", altitude_m:40000000000000000,
    name:{de:"Proxima Centauri", en:"Proxima Centauri"}, sci:"",
    note:"referenz",
    fact:{de:"Der nächste Stern nach der Sonne: 4,24 Lichtjahre bzw. 40 Billionen km entfernt. Selbst Voyager 1 bräuchte dorthin über 70.000 Jahre.",
          en:"The nearest star after the Sun: 4.24 light-years, or 40 trillion km away. Even Voyager 1 would take over 70,000 years to get there."},
    img:"images/proxima.png", credit:"ESO", license:"CC BY",
    source:"https://www.eso.org/public/" },

  /* ---------- NEUERE RAUMFAHRT-EREIGNISSE (2022–2026) ---------- */
  { id:"polaris", cat:"manned", emoji:"👨‍🚀", altitude_m:1408000,
    name:{de:"Polaris Dawn", en:"Polaris Dawn"}, sci:"",
    note:"extremereignis",
    fact:{de:"2024 erreichte diese private SpaceX-Mission 1.408 km Höhe – die höchste bemannte Erdumlaufbahn seit Apollo – und führte den ersten kommerziellen Weltraumspaziergang durch.",
          en:"In 2024 this private SpaceX mission reached 1,408 km – the highest crewed Earth orbit since Apollo – and performed the first commercial spacewalk."},
    img:"images/polaris.png", credit:"SpaceX", license:"CC BY-NC",
    source:"https://www.polarisprogram.com/" },

  { id:"changge6", cat:"unmanned", emoji:"🤖", altitude_m:384400000,
    name:{de:"Chang'e 6", en:"Chang'e 6"}, sci:"",
    note:"extremereignis",
    fact:{de:"Brachte 2024 erstmals Proben von der erdabgewandten Rückseite des Mondes zurück – fast 2 kg Gestein.",
          en:"In 2024 it returned the first-ever samples from the Moon's far side – nearly 2 kg of rock."},
    img:"images/changge6.png", credit:"CNSA", license:"—",
    source:"https://en.wikipedia.org/wiki/Chang%27e_6" },

  { id:"artemis2", cat:"manned", emoji:"🧑‍🚀", altitude_m:390000000,
    name:{de:"Artemis II", en:"Artemis II"}, sci:"",
    note:"extremereignis",
    fact:{de:"Im April 2026 umrundeten vier Astronauten den Mond – die erste bemannte Mondmission seit Apollo 17 (1972).",
          en:"In April 2026 four astronauts looped around the Moon – the first crewed lunar mission since Apollo 17 (1972)."},
    img:"images/artemis2.png", credit:"NASA", license:"Public Domain",
    source:"https://www.nasa.gov/mission/artemis-ii/" },

  { id:"artemis1", cat:"unmanned", emoji:"🚀", altitude_m:432194000,
    name:{de:"Artemis I (Orion)", en:"Artemis I (Orion)"}, sci:"",
    note:"extremereignis",
    fact:{de:"2022 flog die unbemannte Orion-Kapsel 432.194 km weit – weiter als je ein für Menschen gebautes Raumschiff zuvor.",
          en:"In 2022 the uncrewed Orion capsule travelled 432,194 km – farther than any spacecraft built for humans had gone before."},
    img:"images/artemis1.png", credit:"NASA", license:"Public Domain",
    source:"https://www.nasa.gov/artemis-i/" },

  { id:"parker", cat:"unmanned", emoji:"🛰️", altitude_m:143500000000,
    name:{de:"Parker Solar Probe", en:"Parker Solar Probe"}, sci:"",
    note:"extremereignis",
    fact:{de:"Flog im Dezember 2024 bis auf 6,1 Mio. km an die Sonnenoberfläche heran – und ist mit ~690.000 km/h das schnellste je gebaute Objekt.",
          en:"In December 2024 it flew to within 6.1 million km of the Sun's surface – and at ~690,000 km/h is the fastest object ever built."},
    img:"images/parker.png", credit:"NASA/JHUAPL", license:"Public Domain",
    source:"https://science.nasa.gov/mission/parker-solar-probe/" },

  { id:"newhorizons", cat:"unmanned", emoji:"🛰️", altitude_m:9610000000000,
    name:{de:"New Horizons", en:"New Horizons"}, sci:"",
    note:"referenz",
    fact:{de:"Nach dem Pluto-Vorbeiflug 2015 jetzt ~9,6 Mrd. km entfernt im Kuipergürtel – am äußeren Rand des Sonnensystems.",
          en:"After its 2015 Pluto flyby it is now ~9.6 billion km away in the Kuiper Belt – at the outer edge of the Solar System."},
    img:"images/newhorizons.png", credit:"NASA/JHUAPL", license:"Public Domain",
    source:"https://science.nasa.gov/mission/new-horizons/" },

  /* ---------- PIONIERE DER UdSSR ---------- */
  { id:"sputnik1", cat:"unmanned", emoji:"🛰️", altitude_m:940000,
    name:{de:"Sputnik 1", en:"Sputnik 1"}, sci:"",
    note:"extremereignis",
    fact:{de:"Der erste künstliche Satellit der Geschichte (UdSSR, 1957). Sein Piepsen läutete das Weltraumzeitalter ein.",
          en:"The first artificial satellite in history (USSR, 1957). Its beeping signal opened the Space Age."},
    img:"images/sputnik1.png", credit:"—", license:"Public Domain",
    source:"https://en.wikipedia.org/wiki/Sputnik_1" },

  { id:"laika", cat:"unmanned", emoji:"🐕", altitude_m:1660000,
    name:{de:"Laika (Sputnik 2)", en:"Laika (Sputnik 2)"}, sci:"Canis familiaris",
    note:"extremereignis",
    fact:{de:"1957 wurde die Hündin Laika an Bord von Sputnik 2 das erste Lebewesen in einer Erdumlaufbahn – das erste Tier, das wirklich die Erde umrundete.",
          en:"In 1957 the dog Laika aboard Sputnik 2 became the first living being in Earth orbit – the first animal to truly circle the planet."},
    img:"images/laika.png", credit:"—", license:"Public Domain",
    source:"https://en.wikipedia.org/wiki/Laika" },

  { id:"belka_strelka", cat:"unmanned", emoji:"🐕", altitude_m:700000,
    name:{de:"Belka & Strelka", en:"Belka & Strelka"}, sci:"Canis familiaris",
    note:"extremereignis",
    fact:{de:"1960 kehrten die beiden Hündinnen Belka und Strelka als erste Tiere lebend aus der Erdumlaufbahn zurück.",
          en:"In 1960 the dogs Belka and Strelka became the first animals to return alive from Earth orbit."},
    img:"images/belka_strelka.png", credit:"—", license:"Public Domain",
    source:"https://en.wikipedia.org/wiki/Belka_and_Strelka" },

  { id:"gagarin", cat:"manned", emoji:"🧑‍🚀", altitude_m:327000,
    name:{de:"Juri Gagarin (Wostok 1)", en:"Yuri Gagarin (Vostok 1)"}, sci:"",
    note:"extremereignis",
    fact:{de:"1961 umrundete Juri Gagarin als erster Mensch die Erde – ein einziger Orbit in 108 Minuten.",
          en:"In 1961 Yuri Gagarin became the first human to orbit Earth – a single orbit in 108 minutes."},
    img:"images/gagarin.png", credit:"—", license:"Public Domain",
    source:"https://en.wikipedia.org/wiki/Vostok_1" },

  { id:"tereshkova", cat:"manned", emoji:"👩‍🚀", altitude_m:231000,
    name:{de:"Walentina Tereschkowa (Wostok 6)", en:"Valentina Tereshkova (Vostok 6)"}, sci:"",
    note:"extremereignis",
    fact:{de:"1963 wurde Walentina Tereschkowa die erste Frau im Weltraum – allein an Bord für fast drei Tage.",
          en:"In 1963 Valentina Tereshkova became the first woman in space – alone aboard for almost three days."},
    img:"images/tereshkova.png", credit:"—", license:"Public Domain",
    source:"https://en.wikipedia.org/wiki/Vostok_6" },

  { id:"mir", cat:"manned", emoji:"🛰️", altitude_m:350000,
    name:{de:"Raumstation Mir", en:"Mir Space Station"}, sci:"",
    note:"referenz",
    fact:{de:"Die sowjetische Station Mir (1986–2001) war 15 Jahre bemannt und der Vorläufer der ISS.",
          en:"The Soviet station Mir (1986–2001) was crewed for 15 years and the forerunner of the ISS."},
    img:"images/mir.png", credit:"—", license:"Public Domain",
    source:"https://en.wikipedia.org/wiki/Mir" },

  { id:"luna2", cat:"unmanned", emoji:"🌑", altitude_m:384400000,
    name:{de:"Luna 2", en:"Luna 2"}, sci:"",
    note:"extremereignis",
    fact:{de:"1959 schlug Luna 2 als erstes von Menschen gebautes Objekt auf dem Mond ein – das erste Mal, dass wir einen anderen Himmelskörper erreichten.",
          en:"In 1959 Luna 2 became the first human-made object to reach the Moon – the first time we touched another celestial body."},
    img:"images/luna2.png", credit:"—", license:"Public Domain",
    source:"https://en.wikipedia.org/wiki/Luna_2" },

  { id:"venera7", cat:"unmanned", emoji:"🛰️", altitude_m:170000000000,
    name:{de:"Venera 7", en:"Venera 7"}, sci:"",
    note:"extremereignis",
    fact:{de:"1970 landete Venera 7 auf der Venus – die erste weiche Landung auf einem anderen Planeten überhaupt.",
          en:"In 1970 Venera 7 landed on Venus – the first-ever soft landing on another planet."},
    img:"images/venera7.png", credit:"—", license:"Public Domain",
    source:"https://en.wikipedia.org/wiki/Venera_7" },

  /* ---------- KOSMISCHE DISTANZEN ---------- */
  { id:"galaxis", cat:"cosmic", emoji:"🌌", altitude_m:246000000000000000000,
    name:{de:"Zentrum der Milchstraße", en:"Centre of the Milky Way"}, sci:"",
    note:"referenz",
    fact:{de:"Rund 26.000 Lichtjahre entfernt. Im Herzen unserer Galaxie sitzt ein schwarzes Loch mit 4 Mio. Sonnenmassen.",
          en:"About 26,000 light-years away. At the heart of our galaxy sits a black hole of 4 million solar masses."},
    img:"images/galaxis.png", credit:"ESO", license:"CC BY",
    source:"https://en.wikipedia.org/wiki/Galactic_Center" },

  { id:"andromeda", cat:"cosmic", emoji:"🌌", altitude_m:23650000000000000000000,
    name:{de:"Andromeda-Galaxie", en:"Andromeda Galaxy"}, sci:"",
    note:"referenz",
    fact:{de:"Die nächste große Galaxie, ~2,5 Mio. Lichtjahre entfernt – das fernste Objekt, das man mit bloßem Auge sehen kann.",
          en:"The nearest large galaxy, ~2.5 million light-years away – the most distant object visible to the naked eye."},
    img:"images/andromeda.png", credit:"NASA/ESA", license:"Public Domain",
    source:"https://en.wikipedia.org/wiki/Andromeda_Galaxy" },

  { id:"universum", cat:"cosmic", emoji:"🌌", altitude_m:439900000000000000000000000,
    name:{de:"Rand des beobachtbaren Universums", en:"Edge of the observable universe"}, sci:"",
    note:"extremereignis",
    fact:{de:"Das älteste Licht ist 13,8 Mrd. Jahre alt – doch durch die Ausdehnung des Alls liegt sein Ursprung heute ~46,5 Mrd. Lichtjahre entfernt. Weiter können wir prinzipiell nicht sehen.",
          en:"The oldest light is 13.8 billion years old – but cosmic expansion has carried its origin to ~46.5 billion light-years away today. We cannot see any farther, even in principle."},
    img:"images/universum.png", credit:"NASA/WMAP", license:"Public Domain",
    source:"https://en.wikipedia.org/wiki/Observable_universe" },

  /* ===================== SONNENSYSTEM: KLEINKÖRPER & RAND ===================== */
  { id:"asteroidbelt", cat:"reference", emoji:"🪨", altitude_m:2.7*AU,
    name:{de:"Asteroidengürtel", en:"Asteroid Belt"}, sci:"", note:"referenz",
    fact:{de:"Zwischen Mars und Jupiter kreisen Millionen Felsbrocken – Reste, aus denen nie ein Planet wurde.",
          en:"Between Mars and Jupiter orbit millions of rocks – leftovers that never became a planet."},
    img:"images/asteroidbelt.jpg", credit:"NASA", license:"Public Domain", nasa:"asteroid belt",
    source:"https://science.nasa.gov/solar-system/asteroids/" },

  { id:"ceres", cat:"planet", emoji:"⚪", altitude_m:2.77*AU,
    name:{de:"Ceres", en:"Ceres"}, sci:"", note:"referenz",
    fact:{de:"Der größte Körper des Asteroidengürtels und einziger Zwergplanet im inneren Sonnensystem – mit hellen Salzflecken.",
          en:"The largest body in the asteroid belt and the only dwarf planet in the inner Solar System – with bright salt deposits."},
    img:"images/ceres.jpg", credit:"NASA/JPL", license:"Public Domain", nasa:"Ceres Dawn Occator",
    source:"https://science.nasa.gov/dwarf-planets/ceres/" },

  { id:"psyche", cat:"reference", emoji:"🪨", altitude_m:2.9*AU,
    name:{de:"Asteroid Psyche", en:"Asteroid Psyche"}, sci:"", note:"referenz",
    fact:{de:"Ein metallreicher Asteroid – vielleicht der freigelegte Eisenkern eines zerstörten Protoplaneten. Eine NASA-Sonde ist unterwegs.",
          en:"A metal-rich asteroid – perhaps the exposed iron core of a shattered protoplanet. A NASA probe is on its way."},
    img:"images/psyche.jpg", credit:"NASA/JPL", license:"Public Domain", nasa:"asteroid 16 Psyche",
    source:"https://science.nasa.gov/solar-system/asteroids/16-psyche/" },

  { id:"comet67p", cat:"reference", emoji:"☄️", altitude_m:5.7*AU,
    name:{de:"Komet 67P", en:"Comet 67P"}, sci:"", note:"extremereignis",
    fact:{de:"Auf diesem „Gummienten“-Kometen landete 2014 mit Philae erstmals eine Sonde – Ziel der ESA-Mission Rosetta.",
          en:"In 2014 the Philae lander touched down on this 'rubber-duck' comet – the target of ESA's Rosetta mission."},
    img:"images/comet67p.jpg", credit:"ESA/Rosetta", license:"CC BY-SA", nasa:"comet 67P Churyumov Gerasimenko",
    source:"https://science.nasa.gov/solar-system/comets/67p-churyumov-gerasimenko/" },

  { id:"halley", cat:"reference", emoji:"☄️", altitude_m:35*AU,
    name:{de:"Halleyscher Komet", en:"Halley's Comet"}, sci:"", note:"referenz",
    fact:{de:"Der berühmteste Komet, seit 240 v. Chr. dokumentiert. Alle 76 Jahre kehrt er wieder – nächstes Mal 2061.",
          en:"The most famous comet, recorded since 240 BC. It returns every 76 years – next in 2061."},
    img:"images/halley.jpg", credit:"NASA", license:"Public Domain", nasa:"Halley's Comet",
    source:"https://science.nasa.gov/solar-system/comets/1p-halley/" },

  { id:"arrokoth", cat:"reference", emoji:"🪨", altitude_m:44*AU,
    name:{de:"Arrokoth", en:"Arrokoth"}, sci:"", note:"extremereignis",
    fact:{de:"Das fernste je von einer Sonde besuchte Objekt (New Horizons, 2019) – ein 4,5 Mrd. Jahre alter „Schneemann“.",
          en:"The most distant object ever visited by a probe (New Horizons, 2019) – a 4.5-billion-year-old 'snowman'."},
    img:"images/arrokoth.jpg", credit:"NASA/JHUAPL", license:"Public Domain", nasa:"Arrokoth New Horizons",
    source:"https://science.nasa.gov/resource/arrokoth-2014-mu69/" },

  { id:"oumuamua", cat:"reference", emoji:"🛸", altitude_m:40*AU,
    name:{de:"ʻOumuamua", en:"ʻOumuamua"}, sci:"", note:"extremereignis",
    fact:{de:"Der erste bestätigte interstellare Besucher (2017) – ein zigarrenförmiges Objekt aus einem anderen Sternsystem.",
          en:"The first confirmed interstellar visitor (2017) – a cigar-shaped object from another star system."},
    img:"images/oumuamua.jpg", credit:"ESO/M. Kornmesser", license:"CC BY", nasa:"Oumuamua interstellar object",
    source:"https://science.nasa.gov/solar-system/comets/oumuamua/" },

  { id:"eris", cat:"planet", emoji:"⚪", altitude_m:96*AU,
    name:{de:"Eris", en:"Eris"}, sci:"", note:"referenz",
    fact:{de:"Massereicher als Pluto – seine Entdeckung 2005 zwang die Astronomie, „Planet“ neu zu definieren.",
          en:"More massive than Pluto – its 2005 discovery forced astronomers to redefine the word 'planet'."},
    img:"images/eris.jpg", credit:"NASA/JPL", license:"Public Domain", nasa:"dwarf planet Eris",
    source:"https://science.nasa.gov/dwarf-planets/eris/" },

  { id:"sedna", cat:"planet", emoji:"⚪", altitude_m:83*AU,
    name:{de:"Sedna", en:"Sedna"}, sci:"", note:"unsicher",
    fact:{de:"Ein Zwergplanet auf extremer Bahn: ein Umlauf dauert 11.400 Jahre und führt bis 937 AE hinaus.",
          en:"A dwarf planet on an extreme orbit: one lap takes 11,400 years and reaches out to 937 AU."},
    img:"images/sedna.jpg", credit:"NASA/JPL", license:"Public Domain", nasa:"Sedna dwarf planet",
    source:"https://science.nasa.gov/solar-system/planets/dwarf-planets/" },

  { id:"heliopause", cat:"reference", emoji:"🛑", altitude_m:120*AU,
    name:{de:"Heliopause", en:"Heliopause"}, sci:"", note:"referenz",
    fact:{de:"Die wahre Grenze des Sonnensystems: hier endet der Sonnenwind. Voyager 1 flog 2012 hindurch in den interstellaren Raum.",
          en:"The true edge of the Solar System: here the solar wind ends. Voyager 1 crossed it in 2012 into interstellar space."},
    img:"images/heliopause.jpg", credit:"NASA", license:"Public Domain", nasa:"heliopause heliosphere Voyager",
    source:"https://science.nasa.gov/heliophysics/focus-areas/heliosphere/" },

  { id:"pioneer10", cat:"unmanned", emoji:"🛰️", altitude_m:140*AU,
    name:{de:"Pioneer 10", en:"Pioneer 10"}, sci:"", note:"referenz",
    fact:{de:"Eine der ersten interstellaren Sonden (1972) – die erste, die den Asteroidengürtel durchquerte und Jupiter besuchte. Trägt eine Plakette für Außerirdische.",
          en:"One of the first interstellar probes (1972) – the first to cross the asteroid belt and visit Jupiter. It carries a plaque for aliens."},
    img:"images/pioneer10.jpg", credit:"NASA", license:"Public Domain", nasa:"Pioneer 10 spacecraft plaque",
    source:"https://science.nasa.gov/mission/pioneer-10/" },

  { id:"oortcloud", cat:"reference", emoji:"☁️", altitude_m:40000*AU,
    name:{de:"Oortsche Wolke", en:"Oort Cloud"}, sci:"", note:"unsicher",
    fact:{de:"Eine kugelförmige Hülle aus Milliarden Kometen, die das Sonnensystem umgibt – ihr Rand reicht fast bis zum nächsten Stern.",
          en:"A spherical shell of billions of comets surrounding the Solar System – its edge reaches almost to the next star."},
    img:"images/oortcloud.jpg", credit:"NASA", license:"Public Domain", nasa:"Oort cloud",
    source:"https://science.nasa.gov/solar-system/oort-cloud/" },

  /* ===================== INTERSTELLARE NACHBARSCHAFT ===================== */
  { id:"alphacentauri", cat:"star", emoji:"⭐", altitude_m:4.37*LY,
    name:{de:"Alpha Centauri", en:"Alpha Centauri"}, sci:"", note:"referenz",
    fact:{de:"Das nächste Sternsystem: drei Sonnen (A, B und Proxima), die einander umkreisen – Ziel künftiger interstellarer Sonden.",
          en:"The nearest star system: three suns (A, B and Proxima) orbiting each other – target of future interstellar probes."},
    img:"images/alphacentauri.jpg", credit:"NASA/ESA", license:"Public Domain", nasa:"Alpha Centauri",
    source:"https://science.nasa.gov/exoplanets/alpha-centauri/" },

  { id:"proximab", cat:"exoplanet", emoji:"🌍", altitude_m:4.24*LY,
    name:{de:"Proxima Centauri b", en:"Proxima Centauri b"}, sci:"", note:"extremereignis",
    fact:{de:"Der erdnächste Exoplanet, in der habitablen Zone des nächsten Sterns – könnte flüssiges Wasser besitzen.",
          en:"The closest exoplanet to Earth, in the habitable zone of the nearest star – it could hold liquid water."},
    img:"images/proximab.jpg", credit:"ESO/M. Kornmesser", license:"CC BY", nasa:"Proxima Centauri b",
    source:"https://science.nasa.gov/exoplanet-catalog/proxima-centauri-b/" },

  { id:"barnard", cat:"star", emoji:"🔴", altitude_m:5.96*LY,
    name:{de:"Barnards Stern", en:"Barnard's Star"}, sci:"", note:"referenz",
    fact:{de:"Ein roter Zwerg mit der schnellsten bekannten Eigenbewegung am Himmel – er „rast“ über das Firmament.",
          en:"A red dwarf with the fastest known proper motion in the sky – it visibly races across the heavens."},
    img:"images/barnard.jpg", credit:"NASA/ESA", license:"Public Domain", nasa:"Barnard's Star",
    source:"https://science.nasa.gov/exoplanet-catalog/barnards-star-b/" },

  { id:"luhman16", cat:"star", emoji:"🟤", altitude_m:6.5*LY,
    name:{de:"Luhman 16", en:"Luhman 16"}, sci:"", note:"referenz",
    fact:{de:"Das nächste Paar Brauner Zwerge – „gescheiterte Sterne“ mit jupiterähnlichen Wolkenbändern und wechselndem Wetter.",
          en:"The nearest pair of brown dwarfs – 'failed stars' with Jupiter-like cloud bands and changing weather."},
    img:"images/luhman16.jpg", credit:"NASA/JPL", license:"Public Domain", nasa:"Luhman 16 brown dwarf",
    source:"https://science.nasa.gov/" },

  { id:"sirius", cat:"star", emoji:"⭐", altitude_m:8.6*LY,
    name:{de:"Sirius", en:"Sirius"}, sci:"", note:"referenz",
    fact:{de:"Der hellste Stern am Nachthimmel – mit einem winzigen Begleiter, dem Weißen Zwerg Sirius B: Sonnenmasse in Erdgröße.",
          en:"The brightest star in the night sky – with a tiny companion, the white dwarf Sirius B: a Sun's mass squeezed to Earth's size."},
    img:"images/sirius.jpg", credit:"NASA/ESA Hubble", license:"Public Domain", nasa:"Sirius A B white dwarf",
    source:"https://science.nasa.gov/" },

  { id:"epsiloneridani", cat:"star", emoji:"🟠", altitude_m:10.5*LY,
    name:{de:"Epsilon Eridani", en:"Epsilon Eridani"}, sci:"", note:"referenz",
    fact:{de:"Ein junger sonnenähnlicher Stern mit Asteroidengürteln und Planeten – wie ein Sonnensystem in der Entstehung.",
          en:"A young Sun-like star with asteroid belts and planets – like a solar system in the making."},
    img:"images/epsiloneridani.jpg", credit:"NASA/JPL", license:"Public Domain", nasa:"Epsilon Eridani planetary system",
    source:"https://science.nasa.gov/" },

  { id:"tauceti", cat:"star", emoji:"🟡", altitude_m:11.9*LY,
    name:{de:"Tau Ceti", en:"Tau Ceti"}, sci:"", note:"referenz",
    fact:{de:"Der nächste einzelne sonnenähnliche Stern – ein klassisches Ziel der Suche nach außerirdischem Leben (SETI).",
          en:"The nearest single Sun-like star – a classic target in the search for extraterrestrial life (SETI)."},
    img:"images/tauceti.jpg", credit:"ESO", license:"CC BY", nasa:"Tau Ceti star system",
    source:"https://science.nasa.gov/" },

  { id:"vega", cat:"star", emoji:"⭐", altitude_m:25*LY,
    name:{de:"Wega (Vega)", en:"Vega"}, sci:"", note:"referenz",
    fact:{de:"Einer der hellsten Sterne am Himmel, von einer Staubscheibe umgeben – er rotiert so schnell, dass er abgeplattet ist.",
          en:"One of the brightest stars in the sky, ringed by a dust disk – it spins so fast that it bulges at the equator."},
    img:"images/vega.jpg", credit:"NASA/JPL", license:"Public Domain", nasa:"Vega star debris disk",
    source:"https://science.nasa.gov/" },

  { id:"trappist1", cat:"exoplanet", emoji:"🪐", altitude_m:40.7*LY,
    name:{de:"TRAPPIST-1", en:"TRAPPIST-1"}, sci:"", note:"extremereignis",
    fact:{de:"Ein winziger Zwergstern mit sieben erdgroßen Planeten – drei davon in der habitablen Zone. Bestes bekanntes Mehrplanetensystem.",
          en:"A tiny dwarf star with seven Earth-sized planets – three in the habitable zone. The best known multi-planet system."},
    img:"images/trappist1.jpg", credit:"NASA/JPL", license:"Public Domain", nasa:"TRAPPIST-1 system",
    source:"https://science.nasa.gov/exoplanets/trappist1/" },

  { id:"cancri55e", cat:"exoplanet", emoji:"🔶", altitude_m:41*LY,
    name:{de:"55 Cancri e", en:"55 Cancri e"}, sci:"", note:"referenz",
    fact:{de:"Eine glühende Lavawelt, möglicherweise kohlenstoffreich („Diamantplanet“). Ein Jahr dauert nur 18 Stunden.",
          en:"A glowing lava world, possibly carbon-rich (a 'diamond planet'). One year lasts just 18 hours."},
    img:"images/cancri55e.jpg", credit:"NASA/JPL", license:"Public Domain", nasa:"55 Cancri e lava planet",
    source:"https://science.nasa.gov/exoplanet-catalog/55-cancri-e/" },

  { id:"fiftyonepeg", cat:"exoplanet", emoji:"🪐", altitude_m:50*LY,
    name:{de:"51 Pegasi b", en:"51 Pegasi b"}, sci:"", note:"extremereignis",
    fact:{de:"Der erste Exoplanet um einen sonnenähnlichen Stern (1995) – die Entdeckung brachte 2019 den Physik-Nobelpreis.",
          en:"The first exoplanet found around a Sun-like star (1995) – the discovery won the 2019 Nobel Prize in Physics."},
    img:"images/fiftyonepeg.jpg", credit:"ESO/M. Kornmesser", license:"CC BY", nasa:"51 Pegasi b hot Jupiter",
    source:"https://science.nasa.gov/exoplanet-catalog/51-pegasi-b/" },

  { id:"bpm37093", cat:"star", emoji:"💎", altitude_m:53*LY,
    name:{de:"„Lucy“ – der Diamantstern", en:"'Lucy' – the Diamond Star"}, sci:"BPM 37093", note:"referenz",
    fact:{de:"Ein Weißer Zwerg aus kristallisiertem Kohlenstoff – im Grunde ein erdgroßer Diamant, benannt nach dem Beatles-Song.",
          en:"A white dwarf made of crystallised carbon – essentially an Earth-sized diamond, named after the Beatles song."},
    img:"images/bpm37093.jpg", credit:"NASA", license:"Public Domain", nasa:"white dwarf crystal diamond star",
    source:"https://science.nasa.gov/" },

  { id:"rogueplanet", cat:"exoplanet", emoji:"🌑", altitude_m:80*LY,
    name:{de:"Heimatloser Planet", en:"Rogue Planet"}, sci:"", note:"unsicher",
    fact:{de:"Planeten ohne Stern, allein durch die Dunkelheit treibend – möglicherweise gibt es mehr von ihnen als Sterne in der Galaxie.",
          en:"Planets with no star, drifting alone through the dark – there may be more of them than there are stars in the galaxy."},
    img:"images/rogueplanet.jpg", credit:"NASA/JPL", license:"Public Domain", nasa:"rogue planet free floating",
    source:"https://science.nasa.gov/" },

  { id:"kepler16b", cat:"exoplanet", emoji:"🪐", altitude_m:245*LY,
    name:{de:"Kepler-16b „Tatooine“", en:"Kepler-16b 'Tatooine'"}, sci:"", note:"referenz",
    fact:{de:"Ein Planet mit zwei Sonnen am Himmel – wie Luke Skywalkers Heimatwelt aus Star Wars, aber real.",
          en:"A planet with two suns in its sky – like Luke Skywalker's home world from Star Wars, but real."},
    img:"images/kepler16b.jpg", credit:"NASA/JPL", license:"Public Domain", nasa:"Kepler-16b two suns",
    source:"https://science.nasa.gov/exoplanet-catalog/kepler-16-b/" },

  { id:"hd189733b", cat:"exoplanet", emoji:"🔵", altitude_m:64.5*LY,
    name:{de:"HD 189733 b", en:"HD 189733 b"}, sci:"", note:"referenz",
    fact:{de:"Ein tiefblauer Gasriese, auf dem es Glas regnet – seitwärts, mit 7.000 km/h Sturm.",
          en:"A deep-blue gas giant where it rains glass – sideways, in 7,000 km/h winds."},
    img:"images/hd189733b.jpg", credit:"NASA/ESA", license:"Public Domain", nasa:"HD 189733 b blue planet",
    source:"https://science.nasa.gov/exoplanet-catalog/hd-189733-b/" },

  { id:"kelt9b", cat:"exoplanet", emoji:"🔥", altitude_m:670*LY,
    name:{de:"KELT-9b", en:"KELT-9b"}, sci:"", note:"extremereignis",
    fact:{de:"Der heißeste bekannte Planet: ~4.300 °C – heißer als manche Sterne. Eisen verdampft in seiner Atmosphäre.",
          en:"The hottest known planet: ~4,300 °C – hotter than some stars. Iron vaporises in its atmosphere."},
    img:"images/kelt9b.jpg", credit:"NASA/JPL", license:"Public Domain", nasa:"KELT-9b hottest exoplanet",
    source:"https://science.nasa.gov/exoplanet-catalog/kelt-9-b/" },

  { id:"tres2b", cat:"exoplanet", emoji:"⚫", altitude_m:750*LY,
    name:{de:"TrES-2b – der dunkelste Planet", en:"TrES-2b – the darkest planet"}, sci:"", note:"referenz",
    fact:{de:"Schwärzer als Kohle: dieser Planet schluckt über 99 % des Lichts, das auf ihn fällt – glüht aber matt rot.",
          en:"Blacker than coal: this planet swallows over 99% of the light hitting it – yet glows a dim red."},
    img:"images/tres2b.jpg", credit:"NASA/JPL", license:"Public Domain", nasa:"TrES-2b darkest exoplanet",
    source:"https://science.nasa.gov/exoplanet-catalog/tres-2-b/" },

  /* ===================== DIE MILCHSTRASSE ===================== */
  { id:"hyades", cat:"cluster", emoji:"✨", altitude_m:153*LY,
    name:{de:"Hyaden", en:"Hyades"}, sci:"", note:"referenz",
    fact:{de:"Der nächste offene Sternhaufen – eine V-förmige Sternengruppe, die das „Gesicht“ des Stiers bildet.",
          en:"The nearest open star cluster – a V-shaped group of stars forming the 'face' of Taurus the Bull."},
    img:"images/hyades.jpg", credit:"NASA/ESA", license:"Public Domain", nasa:"Hyades star cluster",
    source:"https://science.nasa.gov/" },

  { id:"pleiades", cat:"cluster", emoji:"✨", altitude_m:444*LY,
    name:{de:"Plejaden (Siebengestirn)", en:"Pleiades"}, sci:"", note:"referenz",
    fact:{de:"Über 1.000 junge, heißblaue Sterne in einem Schleier aus Staub – seit der Antike als „Sieben Schwestern“ bekannt.",
          en:"Over 1,000 young, hot-blue stars wrapped in dust – known since antiquity as the 'Seven Sisters'."},
    img:"images/pleiades.jpg", credit:"NASA/ESA", license:"Public Domain", nasa:"Pleiades star cluster",
    source:"https://science.nasa.gov/" },

  { id:"antares", cat:"star", emoji:"🔴", altitude_m:550*LY,
    name:{de:"Antares", en:"Antares"}, sci:"", note:"referenz",
    fact:{de:"Ein roter Überriese mit ~700-fachem Sonnenradius – sein Name bedeutet „Gegen-Mars“ wegen seiner roten Farbe.",
          en:"A red supergiant about 700 times the Sun's radius – its name means 'rival of Mars' for its red colour."},
    img:"images/antares.jpg", credit:"ESO", license:"CC BY", nasa:"Antares red supergiant",
    source:"https://www.eso.org/public/" },

  { id:"helixnebula", cat:"nebula", emoji:"🌫️", altitude_m:650*LY,
    name:{de:"Helixnebel („Auge Gottes“)", en:"Helix Nebula"}, sci:"", note:"referenz",
    fact:{de:"Ein sterbender Stern, der seine Hüllen ins All bläst – sieht aus wie ein gigantisches Auge.",
          en:"A dying star blowing its shells into space – it looks like a giant eye staring back."},
    img:"images/helixnebula.jpg", credit:"NASA/ESA Hubble", license:"Public Domain", nasa:"Helix Nebula",
    source:"https://science.nasa.gov/" },

  { id:"betelgeuse", cat:"star", emoji:"🔴", altitude_m:640*LY,
    name:{de:"Beteigeuze", en:"Betelgeuse"}, sci:"", note:"referenz",
    fact:{de:"Ein roter Überriese, der bis über die Marsbahn reichen würde – er könnte jederzeit als Supernova explodieren.",
          en:"A red supergiant that would engulf the orbit of Mars – it could explode as a supernova at any time."},
    img:"images/betelgeuse.jpg", credit:"ESO", license:"CC BY", nasa:"Betelgeuse red supergiant",
    source:"https://www.eso.org/public/" },

  { id:"vela", cat:"nebula", emoji:"⚡", altitude_m:815*LY,
    name:{de:"Vela-Supernova-Überrest", en:"Vela Supernova Remnant"}, sci:"", note:"referenz",
    fact:{de:"Die Trümmer einer Sternexplosion vor 11.000 Jahren – im Kern rotiert ein Pulsar 11-mal pro Sekunde.",
          en:"The debris of a star that exploded 11,000 years ago – at its core a pulsar spins 11 times a second."},
    img:"images/vela.jpg", credit:"NASA/ESO", license:"Public Domain", nasa:"Vela supernova remnant",
    source:"https://science.nasa.gov/" },

  { id:"rigel", cat:"star", emoji:"🔵", altitude_m:860*LY,
    name:{de:"Rigel", en:"Rigel"}, sci:"", note:"referenz",
    fact:{de:"Ein blauer Überriese mit ~120.000-facher Sonnenleuchtkraft – der hellste Stern im Orion.",
          en:"A blue supergiant shining about 120,000 times brighter than the Sun – the brightest star in Orion."},
    img:"images/rigel.jpg", credit:"NASA", license:"Public Domain", nasa:"Rigel blue supergiant Orion",
    source:"https://science.nasa.gov/" },

  { id:"firstpulsar", cat:"star", emoji:"⚡", altitude_m:1000*LY,
    name:{de:"Erster Pulsar (LGM-1)", en:"First Pulsar (LGM-1)"}, sci:"PSR B1919+21", note:"extremereignis",
    fact:{de:"Der erste je entdeckte Pulsar (1967). Seine präzisen Signale hielt man kurz für ein Signal Außerirdischer – „Little Green Men“.",
          en:"The first pulsar ever discovered (1967). Its precise pulses were briefly thought to be aliens – 'Little Green Men'."},
    img:"images/firstpulsar.jpg", credit:"NASA", license:"Public Domain", nasa:"pulsar neutron star",
    source:"https://en.wikipedia.org/wiki/PSR_B1919%2B21" },

  { id:"orionnebula", cat:"nebula", emoji:"🌌", altitude_m:1344*LY,
    name:{de:"Orionnebel", en:"Orion Nebula"}, sci:"", note:"referenz",
    fact:{de:"Die nächste große Sternenwiege – mit bloßem Auge im Schwert des Orion sichtbar. Hier entstehen gerade neue Sonnen.",
          en:"The nearest great stellar nursery – visible to the naked eye in Orion's sword. New suns are being born here right now."},
    img:"images/orionnebula.jpg", credit:"NASA/ESA Hubble", license:"Public Domain", nasa:"Orion Nebula",
    source:"https://science.nasa.gov/" },

  { id:"gaiabh1", cat:"blackhole", emoji:"⚫", altitude_m:1560*LY,
    name:{de:"Gaia BH1", en:"Gaia BH1"}, sci:"", note:"extremereignis",
    fact:{de:"Das erdnächste bekannte Schwarze Loch – ein „schlafender“ Riese, der gerade nichts verschlingt.",
          en:"The closest known black hole to Earth – a 'sleeping' giant that is currently devouring nothing."},
    img:"images/gaiabh1.jpg", credit:"ESO/NOIRLab", license:"CC BY", nasa:"black hole star orbit",
    source:"https://www.eso.org/public/" },

  { id:"pulsarplanets", cat:"exoplanet", emoji:"⚡", altitude_m:2300*LY,
    name:{de:"Pulsar-Planeten (PSR B1257+12)", en:"Pulsar Planets (PSR B1257+12)"}, sci:"", note:"extremereignis",
    fact:{de:"Die allerersten entdeckten Exoplaneten (1992) – sie umkreisen einen toten, rotierenden Neutronenstern.",
          en:"The very first exoplanets ever discovered (1992) – they orbit a dead, spinning neutron star."},
    img:"images/pulsarplanets.jpg", credit:"NASA/JPL", license:"Public Domain", nasa:"pulsar planets PSR B1257",
    source:"https://science.nasa.gov/" },

  { id:"ringnebula", cat:"nebula", emoji:"🌫️", altitude_m:2560*LY,
    name:{de:"Ringnebel", en:"Ring Nebula"}, sci:"", note:"referenz",
    fact:{de:"Ein fast perfekter Ring aus Gas, abgestoßen von einem sterbenden Stern – in dessen Zentrum ein 70.000 °C heißer Weißer Zwerg glüht.",
          en:"An almost perfect ring of gas shed by a dying star – at its centre glows a 70,000 °C white dwarf."},
    img:"images/ringnebula.jpg", credit:"NASA/ESA JWST", license:"Public Domain", nasa:"Ring Nebula M57",
    source:"https://science.nasa.gov/" },

  { id:"lagoonnebula", cat:"nebula", emoji:"🌌", altitude_m:4100*LY,
    name:{de:"Lagunennebel", en:"Lagoon Nebula"}, sci:"", note:"referenz",
    fact:{de:"Eine riesige leuchtende Wolke, in der ganze Sternhaufen geboren werden – ~100 Lichtjahre breit.",
          en:"A vast glowing cloud where entire star clusters are born – about 100 light-years across."},
    img:"images/lagoonnebula.jpg", credit:"NASA/ESA Hubble", license:"Public Domain", nasa:"Lagoon Nebula M8",
    source:"https://science.nasa.gov/" },

  { id:"uyscuti", cat:"star", emoji:"🔴", altitude_m:5900*LY,
    name:{de:"UY Scuti", en:"UY Scuti"}, sci:"", note:"unsicher",
    fact:{de:"Einer der größten bekannten Sterne – an die Sonnenstelle gesetzt, reichte er fast bis zur Jupiterbahn.",
          en:"One of the largest known stars – placed where the Sun is, it would reach nearly to Jupiter's orbit."},
    img:"images/uyscuti.jpg", credit:"ESO", license:"CC BY", nasa:"UY Scuti red supergiant",
    source:"https://en.wikipedia.org/wiki/UY_Scuti" },

  { id:"mucephei", cat:"star", emoji:"🔴", altitude_m:6000*LY,
    name:{de:"Mu Cephei (Granatstern)", en:"Mu Cephei (Garnet Star)"}, sci:"", note:"unsicher",
    fact:{de:"Ein roter Hyperriese, 100.000-mal leuchtkräftiger als die Sonne – William Herschel nannte ihn den „Granatstern“.",
          en:"A red hypergiant 100,000 times more luminous than the Sun – William Herschel called it the 'Garnet Star'."},
    img:"images/mucephei.jpg", credit:"NASA", license:"Public Domain", nasa:"Mu Cephei garnet star",
    source:"https://en.wikipedia.org/wiki/Mu_Cephei" },

  { id:"crabnebula", cat:"nebula", emoji:"🌫️", altitude_m:6500*LY,
    name:{de:"Krebsnebel", en:"Crab Nebula"}, sci:"", note:"extremereignis",
    fact:{de:"Der Überrest einer Supernova, die chinesische Astronomen 1054 beobachteten – im Kern blinkt ein Pulsar 30-mal pro Sekunde.",
          en:"The remnant of a supernova that Chinese astronomers saw in 1054 – at its core a pulsar flashes 30 times a second."},
    img:"images/crabnebula.jpg", credit:"NASA/ESA JWST", license:"Public Domain", nasa:"Crab Nebula",
    source:"https://science.nasa.gov/" },

  { id:"eaglenebula", cat:"nebula", emoji:"🌌", altitude_m:7000*LY,
    name:{de:"Adlernebel – Säulen der Schöpfung", en:"Eagle Nebula – Pillars of Creation"}, sci:"", note:"referenz",
    fact:{de:"Türme aus Gas und Staub, mehrere Lichtjahre hoch, in denen Sterne entstehen – das berühmteste Bild des Hubble-Teleskops.",
          en:"Towers of gas and dust, light-years tall, where stars are forming – the most famous image Hubble ever took."},
    img:"images/eaglenebula.jpg", credit:"NASA/ESA JWST", license:"Public Domain", nasa:"Pillars of Creation Eagle Nebula",
    source:"https://science.nasa.gov/" },

  { id:"cygnusx1", cat:"blackhole", emoji:"⚫", altitude_m:7200*LY,
    name:{de:"Cygnus X-1", en:"Cygnus X-1"}, sci:"", note:"extremereignis",
    fact:{de:"Das erste je nachgewiesene Schwarze Loch (1964) – es reißt Gas von einem Begleitstern und rotiert nahe der Lichtgeschwindigkeit.",
          en:"The first black hole ever confirmed (1964) – it tears gas from a companion star and spins near light speed."},
    img:"images/cygnusx1.jpg", credit:"NASA/CXC", license:"Public Domain", nasa:"Cygnus X-1 black hole",
    source:"https://science.nasa.gov/" },

  { id:"carinanebula", cat:"nebula", emoji:"🌌", altitude_m:7500*LY,
    name:{de:"Carinanebel", en:"Carina Nebula"}, sci:"", note:"referenz",
    fact:{de:"Eine der größten Sternentstehungsregionen der Galaxie – das James-Webb-Teleskop enthüllte hier „kosmische Klippen“.",
          en:"One of the galaxy's largest star-forming regions – the James Webb telescope revealed its 'Cosmic Cliffs' here."},
    img:"images/carinanebula.jpg", credit:"NASA/ESA JWST", license:"Public Domain", nasa:"Carina Nebula Cosmic Cliffs",
    source:"https://science.nasa.gov/" },

  { id:"etacarinae", cat:"star", emoji:"💥", altitude_m:7500*LY,
    name:{de:"Eta Carinae", en:"Eta Carinae"}, sci:"", note:"extremereignis",
    fact:{de:"Ein extrem instabiles Doppelsternsystem; sein „Großer Ausbruch“ 1843 machte es kurzzeitig zum zweithellsten Stern – ein Supernova-Kandidat.",
          en:"An extremely unstable double-star system; its 'Great Eruption' of 1843 briefly made it the second-brightest star – a supernova candidate."},
    img:"images/etacarinae.jpg", credit:"NASA/ESA Hubble", license:"Public Domain", nasa:"Eta Carinae Homunculus",
    source:"https://science.nasa.gov/" },

  { id:"omegacentauri", cat:"cluster", emoji:"✨", altitude_m:17000*LY,
    name:{de:"Omega Centauri", en:"Omega Centauri"}, sci:"", note:"referenz",
    fact:{de:"Der größte Kugelsternhaufen der Milchstraße – rund 10 Millionen Sterne, dicht gepackt in einer Kugel.",
          en:"The largest globular cluster of the Milky Way – about 10 million stars packed into a sphere."},
    img:"images/omegacentauri.jpg", credit:"NASA/ESA Hubble", license:"Public Domain", nasa:"Omega Centauri globular cluster",
    source:"https://science.nasa.gov/" },

  { id:"fastestpulsar", cat:"star", emoji:"⚡", altitude_m:18000*LY,
    name:{de:"Schnellster Pulsar", en:"Fastest Pulsar"}, sci:"PSR J1748-2446ad", note:"extremereignis",
    fact:{de:"Dreht sich 716-mal pro Sekunde – seine Oberfläche rast mit fast einem Viertel der Lichtgeschwindigkeit.",
          en:"Spins 716 times per second – its surface races at nearly a quarter of the speed of light."},
    img:"images/fastestpulsar.jpg", credit:"NASA", license:"Public Domain", nasa:"millisecond pulsar",
    source:"https://en.wikipedia.org/wiki/PSR_J1748%E2%88%922446ad" },

  { id:"stephenson218", cat:"star", emoji:"🔴", altitude_m:19000*LY,
    name:{de:"Stephenson 2-18", en:"Stephenson 2-18"}, sci:"", note:"unsicher",
    fact:{de:"Ein Kandidat für den größten bekannten Stern – mit ~2.150 Sonnenradien würde er die Saturnbahn verschlingen.",
          en:"A candidate for the largest known star – at ~2,150 solar radii it would swallow Saturn's orbit."},
    img:"images/stephenson218.jpg", credit:"NASA", license:"Public Domain", nasa:"red supergiant largest star",
    source:"https://en.wikipedia.org/wiki/Stephenson_2-18" },

  { id:"fermibubbles", cat:"cosmic", emoji:"🎈", altitude_m:25000*LY,
    name:{de:"Fermi-Blasen", en:"Fermi Bubbles"}, sci:"", note:"referenz",
    fact:{de:"Zwei riesige Gammastrahlen-Blasen, die aus dem Zentrum der Milchstraße quellen – mit der Energie von 100.000 Sternexplosionen.",
          en:"Two giant gamma-ray bubbles billowing out of the Milky Way's centre – carrying the energy of 100,000 star explosions."},
    img:"images/fermibubbles.jpg", credit:"NASA Goddard", license:"Public Domain", nasa:"Fermi Bubbles Milky Way",
    source:"https://www.nasa.gov/" },

  { id:"us708", cat:"star", emoji:"🚀", altitude_m:25000*LY,
    name:{de:"Hypergeschwindigkeitsstern US 708", en:"Hypervelocity Star US 708"}, sci:"", note:"extremereignis",
    fact:{de:"Der schnellste bekannte Stern: mit 1.200 km/s verlässt er die Milchstraße für immer – fortgeschleudert von einer Supernova.",
          en:"The fastest known star: at 1,200 km/s it is leaving the Milky Way forever – flung out by a supernova."},
    img:"images/us708.jpg", credit:"ESO", license:"CC BY", nasa:"hypervelocity star",
    source:"https://en.wikipedia.org/wiki/US_708" },

  { id:"sgrA", cat:"blackhole", emoji:"🕳️", altitude_m:27000*LY,
    name:{de:"Sagittarius A*", en:"Sagittarius A*"}, sci:"", note:"extremereignis",
    fact:{de:"Das supermassereiche Schwarze Loch im Herzen der Milchstraße – 4,3 Millionen Sonnenmassen, 2022 erstmals fotografiert.",
          en:"The supermassive black hole at the heart of the Milky Way – 4.3 million solar masses, first imaged in 2022."},
    img:"images/sgrA.jpg", credit:"EHT Collaboration", license:"CC BY", nasa:"Sagittarius A* black hole Event Horizon",
    source:"https://www.eso.org/public/" },

  { id:"magnetar", cat:"star", emoji:"🧲", altitude_m:50000*LY,
    name:{de:"Magnetar SGR 1806-20", en:"Magnetar SGR 1806-20"}, sci:"", note:"extremereignis",
    fact:{de:"Der stärkste bekannte Magnet im Universum – ein Beben 2004 setzte in 0,2 Sekunden mehr Energie frei als die Sonne in 250.000 Jahren.",
          en:"The strongest known magnet in the universe – a 2004 starquake released more energy in 0.2 seconds than the Sun does in 250,000 years."},
    img:"images/magnetar.jpg", credit:"NASA", license:"Public Domain", nasa:"magnetar SGR 1806-20",
    source:"https://www.nasa.gov/" },

  { id:"milkyway", cat:"galaxy", emoji:"🌌", altitude_m:50000*LY,
    name:{de:"Die Milchstraße", en:"The Milky Way"}, sci:"", note:"referenz",
    fact:{de:"Unsere Heimatgalaxie – eine Spirale mit über 100 Milliarden Sternen, rund 100.000 Lichtjahre im Durchmesser.",
          en:"Our home galaxy – a spiral of over 100 billion stars, about 100,000 light-years across."},
    img:"images/milkyway.jpg", credit:"NASA/JPL", license:"Public Domain", nasa:"Milky Way galaxy",
    source:"https://science.nasa.gov/" },

  /* ===================== LOKALE GRUPPE & GALAXIEN ===================== */
  { id:"lmc", cat:"galaxy", emoji:"🌌", altitude_m:160000*LY,
    name:{de:"Große Magellansche Wolke", en:"Large Magellanic Cloud"}, sci:"", note:"referenz",
    fact:{de:"Eine Begleitgalaxie der Milchstraße – in ihr leuchtete 1987 die nächste Supernova der Neuzeit auf.",
          en:"A companion galaxy of the Milky Way – home to the nearest modern supernova, which blazed up in 1987."},
    img:"images/lmc.jpg", credit:"NASA/ESA", license:"Public Domain", nasa:"Large Magellanic Cloud",
    source:"https://science.nasa.gov/" },

  { id:"tarantula", cat:"nebula", emoji:"🕷️", altitude_m:170000*LY,
    name:{de:"Tarantelnebel", en:"Tarantula Nebula"}, sci:"", note:"referenz",
    fact:{de:"Das größte Sternentstehungsgebiet der kosmischen Nachbarschaft – wäre er so nah wie der Orionnebel, würfe er Schatten.",
          en:"The largest star-forming region in the cosmic neighbourhood – if it were as close as Orion, it would cast shadows."},
    img:"images/tarantula.jpg", credit:"NASA/ESA JWST", license:"Public Domain", nasa:"Tarantula Nebula 30 Doradus",
    source:"https://science.nasa.gov/" },

  { id:"smc", cat:"galaxy", emoji:"🌌", altitude_m:200000*LY,
    name:{de:"Kleine Magellansche Wolke", en:"Small Magellanic Cloud"}, sci:"", note:"referenz",
    fact:{de:"Die zweite Begleitgalaxie der Milchstraße – mit bloßem Auge vom Südhimmel als nebliger Fleck sichtbar.",
          en:"The Milky Way's second companion galaxy – visible to the naked eye from the southern sky as a misty patch."},
    img:"images/smc.jpg", credit:"NASA/ESA", license:"Public Domain", nasa:"Small Magellanic Cloud",
    source:"https://science.nasa.gov/" },

  { id:"triangulum", cat:"galaxy", emoji:"🌌", altitude_m:2.73e6*LY,
    name:{de:"Dreiecksgalaxie", en:"Triangulum Galaxy"}, sci:"M33", note:"referenz",
    fact:{de:"Die drittgrößte Galaxie der Lokalen Gruppe – unter perfekt dunklem Himmel gerade noch mit bloßem Auge zu erahnen.",
          en:"The third-largest galaxy in the Local Group – barely visible to the naked eye under perfectly dark skies."},
    img:"images/triangulum.jpg", credit:"NASA/ESA Hubble", license:"Public Domain", nasa:"Triangulum Galaxy M33",
    source:"https://science.nasa.gov/" },

  { id:"centaurusa", cat:"galaxy", emoji:"🌌", altitude_m:12e6*LY,
    name:{de:"Centaurus A", en:"Centaurus A"}, sci:"", note:"referenz",
    fact:{de:"Die nächste aktive Galaxie – ihr zentrales Schwarzes Loch schießt Materiestrahlen über Millionen Lichtjahre ins All.",
          en:"The nearest active galaxy – its central black hole fires jets of matter millions of light-years into space."},
    img:"images/centaurusa.jpg", credit:"ESO", license:"CC BY", nasa:"Centaurus A galaxy jet",
    source:"https://www.eso.org/public/" },

  { id:"cigargalaxy", cat:"galaxy", emoji:"🌌", altitude_m:12e6*LY,
    name:{de:"Zigarrengalaxie (M82)", en:"Cigar Galaxy (M82)"}, sci:"", note:"referenz",
    fact:{de:"Eine Starburst-Galaxie, die zehnmal schneller Sterne bildet als die Milchstraße – ein kosmisches Feuerwerk.",
          en:"A starburst galaxy forming stars ten times faster than the Milky Way – a cosmic fireworks display."},
    img:"images/cigargalaxy.jpg", credit:"NASA/ESA Hubble", license:"Public Domain", nasa:"Cigar Galaxy M82 starburst",
    source:"https://science.nasa.gov/" },

  { id:"whirlpool", cat:"galaxy", emoji:"🌀", altitude_m:23e6*LY,
    name:{de:"Whirlpool-Galaxie", en:"Whirlpool Galaxy"}, sci:"M51", note:"referenz",
    fact:{de:"Die klassische „Strudel“-Spirale mit perfekten Armen – verformt durch den Tanz mit einer kleinen Begleitgalaxie.",
          en:"The classic 'whirlpool' spiral with perfect arms – shaped by its dance with a small companion galaxy."},
    img:"images/whirlpool.jpg", credit:"NASA/ESA Hubble", license:"Public Domain", nasa:"Whirlpool Galaxy M51",
    source:"https://science.nasa.gov/" },

  { id:"sombrero", cat:"galaxy", emoji:"🌌", altitude_m:31e6*LY,
    name:{de:"Sombrerogalaxie", en:"Sombrero Galaxy"}, sci:"M104", note:"referenz",
    fact:{de:"Von der Kante gesehen sieht diese Galaxie aus wie ein Hut – mit einem milliardenschweren Schwarzen Loch im Zentrum.",
          en:"Seen edge-on, this galaxy looks like a hat – with a billion-solar-mass black hole at its centre."},
    img:"images/sombrero.jpg", credit:"NASA/ESA Hubble", license:"Public Domain", nasa:"Sombrero Galaxy M104",
    source:"https://science.nasa.gov/" },

  /* ===================== GALAXIENHAUFEN, SUPERHAUFEN & STRUKTUR ===================== */
  { id:"virgocluster", cat:"cosmic", emoji:"✦", altitude_m:54e6*LY,
    name:{de:"Virgo-Galaxienhaufen", en:"Virgo Cluster"}, sci:"", note:"referenz",
    fact:{de:"Der nächste große Galaxienhaufen mit ~1.300 Galaxien – sein Zentrum zieht auch unsere Lokale Gruppe an.",
          en:"The nearest large galaxy cluster, with ~1,300 galaxies – its centre even tugs at our own Local Group."},
    img:"images/virgocluster.jpg", credit:"NASA/ESA", license:"Public Domain", nasa:"Virgo Cluster galaxies",
    source:"https://science.nasa.gov/" },

  { id:"m87", cat:"blackhole", emoji:"🕳️", altitude_m:55e6*LY,
    name:{de:"M87* – das erste fotografierte Schwarze Loch", en:"M87* – the first imaged black hole"}, sci:"", note:"extremereignis",
    fact:{de:"6,5 Milliarden Sonnenmassen: 2019 das erste je abgebildete Schwarze Loch – ein glühender Ring um die Dunkelheit.",
          en:"6.5 billion solar masses: in 2019 the first black hole ever imaged – a glowing ring around the darkness."},
    img:"images/m87.jpg", credit:"EHT Collaboration", license:"CC BY", nasa:"M87 black hole Event Horizon Telescope",
    source:"https://www.eso.org/public/" },

  { id:"gw170817", cat:"cosmic", emoji:"💫", altitude_m:130e6*LY,
    name:{de:"Kilonova GW170817", en:"Kilonova GW170817"}, sci:"", note:"extremereignis",
    fact:{de:"2017 verschmolzen hier zwei Neutronensterne – die Gravitationswellen und das Licht zeigten: hier entsteht Gold und Platin.",
          en:"In 2017 two neutron stars merged here – the gravitational waves and light revealed it forges gold and platinum."},
    img:"images/gw170817.jpg", credit:"NASA/ESA", license:"Public Domain", nasa:"neutron star merger kilonova",
    source:"https://www.nasa.gov/" },

  { id:"greatattractor", cat:"cosmic", emoji:"✦", altitude_m:200e6*LY,
    name:{de:"Großer Attraktor", en:"Great Attractor"}, sci:"", note:"unsicher",
    fact:{de:"Eine rätselhafte Massenkonzentration, die unsere gesamte Galaxie und Tausende andere zu sich zieht – verborgen hinter der Milchstraße.",
          en:"A mysterious concentration of mass pulling our entire galaxy and thousands of others toward it – hidden behind the Milky Way."},
    img:"images/greatattractor.jpg", credit:"NASA", license:"Public Domain", nasa:"Great Attractor large scale structure",
    source:"https://en.wikipedia.org/wiki/Great_Attractor" },

  { id:"laniakea", cat:"cosmic", emoji:"✦", altitude_m:250e6*LY,
    name:{de:"Laniakea-Superhaufen", en:"Laniakea Supercluster"}, sci:"", note:"referenz",
    fact:{de:"Unsere kosmische Heimatadresse: ein Superhaufen aus 100.000 Galaxien. „Laniakea“ heißt hawaiianisch „unermesslicher Himmel“.",
          en:"Our cosmic home address: a supercluster of 100,000 galaxies. 'Laniakea' is Hawaiian for 'immense heaven'."},
    img:"images/laniakea.jpg", credit:"Nature/Tully", license:"CC BY", nasa:"Laniakea supercluster",
    source:"https://en.wikipedia.org/wiki/Laniakea_Supercluster" },

  { id:"comacluster", cat:"cosmic", emoji:"✦", altitude_m:320e6*LY,
    name:{de:"Coma-Galaxienhaufen", en:"Coma Cluster"}, sci:"", note:"referenz",
    fact:{de:"Ein dichter Haufen aus über 1.000 Galaxien – an ihm fand man 1933 die ersten Hinweise auf Dunkle Materie.",
          en:"A dense cluster of over 1,000 galaxies – the first hints of dark matter were found here in 1933."},
    img:"images/comacluster.jpg", credit:"NASA/ESA Hubble", license:"Public Domain", nasa:"Coma Cluster galaxies",
    source:"https://science.nasa.gov/" },

  { id:"holm15a", cat:"blackhole", emoji:"🕳️", altitude_m:700e6*LY,
    name:{de:"Holm 15A", en:"Holm 15A"}, sci:"", note:"unsicher",
    fact:{de:"Das massereichste Schwarze Loch im näheren Universum – 40 Milliarden Sonnenmassen, vermutlich aus zwei verschmolzenen entstanden.",
          en:"The most massive black hole in the nearby universe – 40 billion solar masses, likely born from two that merged."},
    img:"images/holm15a.jpg", credit:"ESO", license:"CC BY", nasa:"Holm 15A black hole",
    source:"https://en.wikipedia.org/wiki/Holmberg_15A" },

  { id:"bootesvoid", cat:"cosmic", emoji:"⚫", altitude_m:700e6*LY,
    name:{de:"Boötes-Void („die große Leere“)", en:"Boötes Void"}, sci:"", note:"referenz",
    fact:{de:"Eine fast leere Region, 330 Mio. Lichtjahre groß – wären wir dort, hätten wir die anderen Galaxien lange für nicht existent gehalten.",
          en:"An almost empty region 330 million light-years wide – if we lived there, we'd long have thought we were alone in the cosmos."},
    img:"images/bootesvoid.jpg", credit:"NASA", license:"Public Domain", nasa:"cosmic void large scale structure",
    source:"https://en.wikipedia.org/wiki/Bo%C3%B6tes_void" },

  { id:"sloanwall", cat:"cosmic", emoji:"🧱", altitude_m:1e9*LY,
    name:{de:"Sloan Great Wall", en:"Sloan Great Wall"}, sci:"", note:"referenz",
    fact:{de:"Eine gigantische Mauer aus Galaxien, ~1,4 Milliarden Lichtjahre lang – eine der größten Strukturen des Universums.",
          en:"A gigantic wall of galaxies about 1.4 billion light-years long – one of the largest structures in the universe."},
    img:"images/sloanwall.jpg", credit:"SDSS", license:"CC BY", nasa:"Sloan Great Wall galaxy filament",
    source:"https://en.wikipedia.org/wiki/Sloan_Great_Wall" },

  { id:"gw150914", cat:"cosmic", emoji:"〰️", altitude_m:1.3e9*LY,
    name:{de:"Erste Gravitationswelle (GW150914)", en:"First Gravitational Wave (GW150914)"}, sci:"", note:"extremereignis",
    fact:{de:"2015 zum ersten Mal direkt gemessen: das Beben der Raumzeit von zwei verschmelzenden Schwarzen Löchern – 1,3 Mrd. Jahre unterwegs.",
          en:"First directly measured in 2015: the tremor in spacetime from two merging black holes – travelling for 1.3 billion years."},
    img:"images/gw150914.jpg", credit:"LIGO/Caltech", license:"CC BY", nasa:"gravitational waves black hole merger LIGO",
    source:"https://www.ligo.caltech.edu/" },

  /* ===================== FRONTIER & MYSTERIEN ===================== */
  { id:"quasar3c273", cat:"cosmic", emoji:"💡", altitude_m:2.4e9*LY,
    name:{de:"Quasar 3C 273", en:"Quasar 3C 273"}, sci:"", note:"extremereignis",
    fact:{de:"Der erste erkannte Quasar (1963) – ein Schwarzes Loch, das so gefräßig ist, dass es heller leuchtet als 1.000 Milchstraßen.",
          en:"The first quasar ever identified (1963) – a black hole feeding so fiercely that it outshines 1,000 Milky Ways."},
    img:"images/quasar3c273.jpg", credit:"NASA/ESA Hubble", license:"Public Domain", nasa:"quasar 3C 273",
    source:"https://science.nasa.gov/" },

  { id:"frb", cat:"cosmic", emoji:"📡", altitude_m:3e9*LY,
    name:{de:"Schnelle Radioblitze (FRBs)", en:"Fast Radio Bursts"}, sci:"", note:"unsicher",
    fact:{de:"Millisekunden-Blitze aus den Tiefen des Alls, die in einem Augenblick mehr Energie abstrahlen als die Sonne in Tagen – Ursprung noch rätselhaft.",
          en:"Millisecond flashes from the depths of space, each releasing more energy in an instant than the Sun does in days – their origin still a mystery."},
    img:"images/frb.jpg", credit:"NASA", license:"Public Domain", nasa:"fast radio burst",
    source:"https://en.wikipedia.org/wiki/Fast_radio_burst" },

  { id:"darkmatter", cat:"cosmic", emoji:"🌑", altitude_m:4e9*LY,
    name:{de:"Dunkle Materie", en:"Dark Matter"}, sci:"", note:"referenz",
    fact:{de:"Unsichtbar, aber überall: ~27 % des Universums bestehen aus dunkler Materie, deren Schwerkraft die Galaxien zusammenhält.",
          en:"Invisible yet everywhere: ~27% of the universe is dark matter, whose gravity holds the galaxies together."},
    img:"images/darkmatter.jpg", credit:"NASA/ESA", license:"Public Domain", nasa:"dark matter map",
    source:"https://science.nasa.gov/" },

  { id:"darkenergy", cat:"cosmic", emoji:"✴️", altitude_m:6e9*LY,
    name:{de:"Dunkle Energie", en:"Dark Energy"}, sci:"", note:"referenz",
    fact:{de:"Die größte Unbekannte: ~68 % des Universums sind dunkle Energie, die den Kosmos immer schneller auseinandertreibt.",
          en:"The greatest unknown: ~68% of the universe is dark energy, driving the cosmos apart ever faster."},
    img:"images/darkenergy.jpg", credit:"NASA", license:"Public Domain", nasa:"dark energy accelerating universe",
    source:"https://science.nasa.gov/" },

  { id:"herculescorona", cat:"cosmic", emoji:"🧱", altitude_m:10e9*LY,
    name:{de:"Hercules–Corona-Borealis-Mauer", en:"Hercules–Corona Borealis Great Wall"}, sci:"", note:"unsicher",
    fact:{de:"Die größte bekannte Struktur des Universums – eine Galaxienmauer, die sich über rund 10 Milliarden Lichtjahre erstreckt.",
          en:"The largest known structure in the universe – a wall of galaxies stretching across some 10 billion light-years."},
    img:"images/herculescorona.jpg", credit:"NASA", license:"Public Domain", nasa:"large scale structure universe filament",
    source:"https://en.wikipedia.org/wiki/Hercules%E2%80%93Corona_Borealis_Great_Wall" },

  { id:"ton618", cat:"blackhole", emoji:"🕳️", altitude_m:18.2e9*LY,
    name:{de:"TON 618 – das größte Schwarze Loch", en:"TON 618 – the largest black hole"}, sci:"", note:"unsicher",
    fact:{de:"Mit ~66 Milliarden Sonnenmassen eines der größten bekannten Schwarzen Löcher – sein Ereignishorizont ist größer als unser Sonnensystem.",
          en:"At ~66 billion solar masses, one of the largest known black holes – its event horizon is bigger than our Solar System."},
    img:"images/ton618.jpg", credit:"NASA", license:"Public Domain", nasa:"quasar supermassive black hole",
    source:"https://en.wikipedia.org/wiki/TON_618" },

  { id:"earendel", cat:"star", emoji:"✨", altitude_m:28e9*LY,
    name:{de:"Earendel – der fernste Stern", en:"Earendel – the most distant star"}, sci:"", note:"extremereignis",
    fact:{de:"Der fernste je beobachtete Einzelstern – nur durch eine kosmische Gravitationslinse sichtbar, sein Licht ist fast 13 Mrd. Jahre alt.",
          en:"The most distant single star ever observed – visible only through a cosmic gravitational lens, its light is nearly 13 billion years old."},
    img:"images/earendel.jpg", credit:"NASA/ESA JWST", license:"Public Domain", nasa:"Earendel most distant star",
    source:"https://science.nasa.gov/" },

  { id:"jadesz14", cat:"galaxy", emoji:"🌌", altitude_m:33.6e9*LY,
    name:{de:"JADES-GS-z14-0 – die fernste Galaxie", en:"JADES-GS-z14-0 – the most distant galaxy"}, sci:"", note:"extremereignis",
    fact:{de:"Die fernste bekannte Galaxie: ihr Licht zeigt uns das Universum nur 295 Millionen Jahre nach dem Urknall.",
          en:"The most distant known galaxy: its light shows us the universe just 295 million years after the Big Bang."},
    img:"images/jadesz14.jpg", credit:"NASA/ESA JWST", license:"Public Domain", nasa:"JADES most distant galaxy JWST",
    source:"https://science.nasa.gov/" },

  { id:"cmb", cat:"cosmic", emoji:"🔮", altitude_m:45.6e9*LY,
    name:{de:"Kosmische Hintergrundstrahlung", en:"Cosmic Microwave Background"}, sci:"", note:"extremereignis",
    fact:{de:"Das „Babyfoto“ des Universums: das älteste Licht überhaupt, ausgesandt 380.000 Jahre nach dem Urknall. Dahinter liegt das Unsichtbare.",
          en:"The 'baby photo' of the universe: the oldest light of all, released 380,000 years after the Big Bang. Beyond it lies the unseen."},
    img:"images/cmb.jpg", credit:"ESA/Planck", license:"CC BY", nasa:"cosmic microwave background Planck map",
    source:"https://www.esa.int/Science_Exploration/Space_Science/Planck" },

];

/* Atmosphären-/Raum-Schichten als beschriftete Bänder (Bereiche in Metern). */
const ATMOSPHERE_LAYERS = [
  { name:{de:"Troposphäre",  en:"Troposphere"},  from:0,        to:12000 },
  { name:{de:"Stratosphäre", en:"Stratosphere"}, from:12000,    to:50000 },
  { name:{de:"Mesosphäre",   en:"Mesosphere"},   from:50000,    to:85000 },
  { name:{de:"Thermosphäre", en:"Thermosphere"}, from:85000,    to:600000 },
  { name:{de:"Exosphäre",    en:"Exosphere"},    from:600000,   to:10000000 },
  { name:{de:"Weltraum",     en:"Outer Space"},  from:10000000, to:500000000000000000000000000 },
];

/* Jahr des jeweiligen Rekords/Meilensteins (ab dem Weltraum). */
const SPACE_YEARS = {
  sputnik1:1957, laika:1957, belka_strelka:1960, gagarin:1961, tereshkova:1963,
  x15:1963, geo:1964, gemini11:1966, mond:1969, apollo13:1970, luna2:1959,
  venera7:1970, voyager2:1977, voyager1:1977, gps:1978, mir:1986, hubble:1990,
  curiosity:2012, artemis1:2022, jwst:2021,
  changge6:2024, parker:2024, polaris:2024, newhorizons:2015, artemis2:2026,
  iss:1998,
  // Ikonische Entdeckungs-/Beobachtungsjahre kosmischer Objekte
  ceres:1801, comet67p:2014, arrokoth:2019, oumuamua:2017, eris:2005,
  fiftyonepeg:1995, trappist1:2017, firstpulsar:1967, pulsarplanets:1992,
  cygnusx1:1964, sgrA:2022, quasar3c273:1963, m87:2019, gw150914:2016,
  gw170817:2017, cmb:1965, earendel:2022, jadesz14:2024,
};

/* Erzählerische Akte des Aufstiegs (Bereiche in Metern, mit Banner-Titel). */
const SECTIONS = [
  { name:{de:"Atmosphäre",                    en:"Atmosphere"},               from:0,         to:100000 },
  { name:{de:"Das Sonnensystem",              en:"The Solar System"},         from:100000,    to:0.3*9.4607e15 },
  { name:{de:"Interstellare Nachbarschaft",   en:"Interstellar Neighbourhood"},from:0.3*9.4607e15, to:140*9.4607e15 },
  { name:{de:"Die Milchstraße",               en:"The Milky Way"},            from:140*9.4607e15, to:130000*9.4607e15 },
  { name:{de:"Lokale Gruppe & Galaxien",      en:"Local Group & Galaxies"},   from:130000*9.4607e15, to:45e6*9.4607e15 },
  { name:{de:"Galaxienhaufen & Superhaufen",  en:"Clusters & Superclusters"}, from:45e6*9.4607e15, to:900e6*9.4607e15 },
  { name:{de:"Großräumige Struktur",          en:"Large-scale Structure"},    from:900e6*9.4607e15, to:14e9*9.4607e15 },
  { name:{de:"Die Grenze des Sichtbaren",     en:"The Edge of the Visible"},  from:14e9*9.4607e15, to:50e9*9.4607e15 },
];

/* Stützfarben für den Hintergrund-Gradienten: altitude_m -> [r,g,b]. */
const SKY_COLORS = [
  { alt:0,            c:[150, 205, 235] },  // Boden / heller Himmel
  { alt:1000,         c:[110, 175, 230] },
  { alt:8000,         c:[ 70, 130, 205] },
  { alt:20000,        c:[ 40,  80, 160] },
  { alt:50000,        c:[ 18,  35,  85] },
  { alt:100000,       c:[  6,  12,  40] },  // Kármán-Linie
  { alt:1000000,      c:[  2,   4,  18] },
  { alt:500000000000000000000000000,c:[  0,   0,   4] }, // interstellar bis intergalaktisch
];

/* Sprung-Ziele für das Teleport-Menü. */
const TELEPORT_TARGETS = [
  { alt:0,                  label:{de:"Boden",        en:"Ground"} },
  { alt:11300,              label:{de:"Höchster Vogel", en:"Highest bird"} },
  { alt:100000,             label:{de:"Weltraum",      en:"Space"} },
  { alt:384400000,          label:{de:"Mond",          en:"Moon"} },
  { alt:149600000000,       label:{de:"Sonne",         en:"Sun"} },
  { alt:25800000000000,     label:{de:"Voyager 1",     en:"Voyager 1"} },
  { alt:4.0e16,             label:{de:"Nahe Sterne",   en:"Nearby stars"} },
  { alt:1344*9.4607e15,     label:{de:"Milchstraße",   en:"Milky Way"} },
  { alt:2.5e6*9.4607e15,    label:{de:"Galaxien",      en:"Galaxies"} },
  { alt:250e6*9.4607e15,    label:{de:"Superhaufen",   en:"Superclusters"} },
  { alt:33.6e9*9.4607e15,   label:{de:"Frontier",      en:"Frontier"} },
  { alt:439900000000000000000000000, label:{de:"Rand des Universums", en:"Edge of the universe"} },
];
